package config

var INFISICAL_URL string
var INFISICAL_URL_MANUAL_OVERRIDE string
var INFISICAL_LOGIN_URL string
var INFISICAL_DISABLE_TELEMETRY bool

func init() {
	viper.SetDefault("INFISICAL_DISABLE_TELEMETRY", false)
	viper.BindEnv("INFISICAL_DISABLE_TELEMETRY")
	INFISICAL_DISABLE_TELEMETRY = viper.GetBool("INFISICAL_DISABLE_TELEMETRY")
}
