{{- if not .Values.auth.existingSecretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infisical-agent-proxy.fullname" . }}-auth
  labels:
    {{- include "infisical-agent-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  clientId: {{ .Values.auth.clientId | b64enc | quote }}
  clientSecret: {{ .Values.auth.clientSecret | b64enc | quote }}
{{- end }}
