// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ProjectBotsSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  isActive: z.boolean().default(false),
  encryptedPrivateKey: z.string(),
  publicKey: z.string(),
  iv: z.string(),
  tag: z.string(),
  algorithm: z.string(),
  keyEncoding: z.string(),
  encryptedProjectKey: z.string().optional().nullable(),
  encryptedProjectKeyNonce: z.string().optional().nullable(),
  projectId: z.string().uuid(),
  senderId: z.string().uuid().optional().nullable(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TProjectBots = z.infer<typeof ProjectBotsSchema>;
export type TProjectBotsInsert = Omit<TProjectBots, TImmutableDBKeys>;
export type TProjectBotsUpdate = Partial<Omit<TProjectBots, TImmutableDBKeys>>;
