// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const UserEncryptionKeysSchema = z.object({
  id: z.string().uuid(),
  clientPublicKey: z.string().nullable().optional(),
  serverPrivateKey: z.string().nullable().optional(),
  encryptionVersion: z.number().default(1).nullable().optional(),
  protectedKey: z.string(),
  protectedKeyIV: z.string(),
  protectedKeyTag: z.string(),
  publicKey: z.string(),
  encryptedPrivateKey: z.string(),
  iv: z.string(),
  tag: z.string(),
  salt: z.string(),
  verifier: z.string(),
  userId: z.string().uuid(),
});

export type TUserEncryptionKeys = z.infer<typeof UserEncryptionKeysSchema>;
export type TUserEncryptionKeysInsert = Omit<TUserEncryptionKeys, TImmutableDBKeys>;
export type TUserEncryptionKeysUpdate = Partial<Omit<TUserEncryptionKeys, TImmutableDBKeys>>;
