# Base layer
FROM node:16-alpine

# Set the working directory 
WORKDIR /app

# Copy over dependency files 
COPY package.json ./
COPY package-lock.json ./
COPY yarn.lock ./

# Install 
RUN yarn install 

# Copy over next.js config 
COPY next.config.js ./next.config.js

# Copy all files 
COPY . .

CMD ["yarn", "dev"]