{{- if .Values.secret.create -}}
{{- if not .Values.secret.data }}
{{- fail "secret.data is required when secret.create is true. Please provide key-value pairs for the secret." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "infisical-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
