{{- if and (eq .Values.gateway.enrollMethod "token") .Values.gateway.token.value (not .Values.gateway.token.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infisical-gateway.fullname" . }}-enrollment-token
  labels:
    {{- include "infisical-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.gateway.token.secretKey | default "enrollment-token" }}: {{ .Values.gateway.token.value | b64enc | quote }}
{{- end }}
