{{- if .Values.gateway.listenAddress }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infisical-gateway.fullname" . }}
  labels:
    {{- include "infisical-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "infisical-gateway.servicePort" . }}
      targetPort: {{ include "infisical-gateway.listenPort" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "infisical-gateway.selectorLabels" . | nindent 4 }}
{{- end }}
