apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-wait-for-infisical-schema-migration
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
subjects:
  - kind: ServiceAccount
    name: default 
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: k8s-wait-for-infisical-schema-migration
  apiGroup: rbac.authorization.k8s.io
