{{- $infisicalValues := .Values.infisical }}
{{- if $infisicalValues.autoDatabaseSchemaMigration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-schema-migration-{{ .Release.Revision }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  backoffLimit: 10
  template:
    metadata:
      name: "{{ .Release.Name }}-create-tables"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      {{- if $infisicalValues.redeployOnSecretChange }}
      annotations:
        secret.reloader.stakater.com/reload: {{ $infisicalValues.kubeSecretRef }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "infisical.serviceAccountName" . }}
    {{- if $infisicalValues.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $infisicalValues.image.imagePullSecrets | nindent 6 }}
    {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: infisical-schema-migration
          image: "{{ $infisicalValues.image.repository }}:{{ $infisicalValues.image.tag }}"
          command: ["npm", "run", "migration:latest"]
          env:
          {{- if .Values.postgresql.useExistingPostgresSecret.enabled }}
          - name: DB_CONNECTION_URI
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.useExistingPostgresSecret.existingConnectionStringSecret.name }}
                key: {{ .Values.postgresql.useExistingPostgresSecret.existingConnectionStringSecret.key }}
          {{- end }}
          {{- if .Values.postgresql.enabled }}
          - name: DB_CONNECTION_URI
            value: {{ include "infisical.postgresDBConnectionString" . }}
          {{- end }}
          envFrom:
          - secretRef:
              name: {{ $infisicalValues.kubeSecretRef }}
          {{- with $infisicalValues.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with $infisicalValues.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}