{{- $infisicalValues := .Values.infisical }}
{{- if $infisicalValues.autoDatabaseSchemaMigration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-schema-migration-{{ .Release.Revision }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  backoffLimit: 10
  template:
    metadata:
      name: "{{ .Release.Name }}-create-tables"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: infisical-schema-migration
          image: "{{ $infisicalValues.image.repository }}:{{ $infisicalValues.image.tag }}"
          command: ["npm", "run", "migration:latest"]
          env:
          {{/* requires only DB_CONNECTION_URI, given > built-in > secret */}}
          {{- if hasKey $infisicalValues.config "DB_CONNECTION_URI" -}}
          - name: DB_CONNECTION_URI
            value: {{ $infisicalValues.config.DB_CONNECTION_URI }}
          {{- else if .Values.postgresql.enabled -}}
          - name: DB_CONNECTION_URI
            value: {{ include "infisical.postgresDBConnectionString" . }}
          {{- else -}}
          - name: DB_CONNECTION_URI
            valueFrom:
              secretKeyRef:
                name: {{ $infisicalValues.kubeSecretRef }}
                key: DB_CONNECTION_URI
          {{- end }}
{{- end }}