{{- if .Values.infisical.kubeSecretGenerate.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.infisical.kubeSecretRef }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    {{- include "infisical.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
type: Opaque
stringData:
  {{ toYaml .Values.infisical.kubeSecretGenerate.env | nindent 2 }}
{{- end }}
