export const integrationSlugNameMapping: Record<string, string> = {
  "azure-key-vault": "Azure Key Vault",
  "aws-parameter-store": "AWS Parameter Store",
  "aws-secret-manager": "AWS Secrets Manager",
  heroku: "Heroku",
  vercel: "Vercel",
  netlify: "Netlify",
  github: "GitHub",
  gitlab: "GitLab",
  render: "Render",
  "laravel-forge": "Laravel Forge",
  railway: "Railway",
  flyio: "Fly.io",
  circleci: "CircleCI",
  databricks: "Databricks",
  travisci: "TravisCI",
  supabase: "Supabase",
  checkly: "Checkly",
  qovery: "Qovery",
  "terraform-cloud": "Terraform Cloud",
  teamcity: "TeamCity",
  "hashicorp-vault": "Vault",
  "cloudflare-pages": "Cloudflare Pages",
  "cloudflare-workers": "Cloudflare Workers",
  codefresh: "Codefresh",
  "digital-ocean-app-platform": "Digital Ocean App Platform",
  bitbucket: "Bitbucket",
  "cloud-66": "Cloud 66",
  northflank: "Northflank",
  windmill: "Windmill",
  "gcp-secret-manager": "GCP Secret Manager",
  "hasura-cloud": "Hasura Cloud",
  rundeck: "Rundeck",
  "azure-devops": "Azure DevOps",
  "azure-app-configuration": "Azure App Configuration",
  "octopus-deploy": "Octopus Deploy"
};
