apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalDynamicSecret
metadata:
  name: infisicaldynamicsecret-demo
spec:
  hostAPI: http://localhost:8080/api

  dynamicSecret:
    secretName: dynamic-secret
    projectId: 5cdc4fec-f541-413c-b0bc-4c15572e421e
    secretsPath: /
    environmentSlug: dev

  leaseRevocationPolicy: Revoke # Revoke or None. Revoke will revoke leases created by the operator if the CRD is deleted.
  leaseTTL: 1m # TTL for the leases created. Must be below 24 hours.

  # Reference to the secret that you want to store the lease credentials in. If a secret with the name specified name does not exist, it will automatically be created.
  managedSecretReference:
    secretName: lease
    secretNamespace: default
    creationPolicy: Orphan # Orphan or Owner

  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials # universal-auth-credentials
        secretNamespace: default # default
