FROM node:18-slim
WORKDIR app/
COPY package.json package-lock.json ./
RUN npm ci 
RUN npm cache clean --force
COPY . .

RUN apt-get update && apt-get install -y bash curl && curl -1sLf \
  'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | bash \
  && apt-get update && apt-get install -y infisical=0.8.1


CMD [ "npm", "start" ]
