apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalDynamicSecret
metadata:
  name: infisicaldynamicsecret-demo
spec:
  hostAPI: https://app.infisical.com/api

  dynamicSecret:
    secretName: <dynamic-secret-name>
    projectId: <project-id>
    secretsPath: <secret-path>
    environmentSlug: <env-slug>

  leaseRevocationPolicy: Revoke # Revoke or None. Revoke will revoke leases created by the operator if the CRD is deleted.
  leaseTTL: 1m # TTL for the leases created. Must be below 24 hours.

  # Reference to the secret that you want to store the lease credentials in. If a secret with the name specified name does not exist, it will automatically be created.
  managedSecretReference:
    secretName: lease
    secretNamespace: default
    creationPolicy: Orphan # Orphan or Owner

  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials # universal-auth-credentials
        secretNamespace: default # default
