export { PamResourceAccountsSection } from "./PamResourceAccountsSection";
export { PamResourceConnectionSection } from "./PamResourceConnectionSection";
export { PamResourceDependenciesSection } from "./PamResourceDependenciesSection";
export { PamResourceDetailsSection } from "./PamResourceDetailsSection";
export { PamResourceMetadataSection } from "./PamResourceMetadataSection";
export { PamResourceRelatedResourcesSection } from "./PamResourceRelatedResourcesSection";
export { PamResourceRotationPolicySection } from "./PamResourceRotationPolicySection";
export type { SessionRecordingConfig } from "./PamResourceSessionRecordingSection";
export { PamResourceSessionRecordingSection } from "./PamResourceSessionRecordingSection";
export { PamRotationPolicyModal } from "./PamRotationPolicyModal";
export { PamSessionRecordingModal } from "./PamSessionRecordingModal";
