// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AgentPolicyRulesSchema = z.object({
  id: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  policyId: z.string().uuid(),
  hostPattern: z.string(),
  methods: z.string().array()
});

export type TAgentPolicyRules = z.infer<typeof AgentPolicyRulesSchema>;
export type TAgentPolicyRulesInsert = Omit<z.input<typeof AgentPolicyRulesSchema>, TImmutableDBKeys>;
export type TAgentPolicyRulesUpdate = Partial<Omit<z.input<typeof AgentPolicyRulesSchema>, TImmutableDBKeys>>;
