// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const AgentVaultServiceSubstitutionsSchema = z.object({
  id: z.string().uuid(),
  serviceId: z.string().uuid(),
  placeholder: z.string(),
  surfaces: z.string().array(),
  encryptedValue: zodBuffer,
  position: z.number(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAgentVaultServiceSubstitutions = z.infer<typeof AgentVaultServiceSubstitutionsSchema>;
export type TAgentVaultServiceSubstitutionsInsert = Omit<
  z.input<typeof AgentVaultServiceSubstitutionsSchema>,
  TImmutableDBKeys
>;
export type TAgentVaultServiceSubstitutionsUpdate = Partial<
  Omit<z.input<typeof AgentVaultServiceSubstitutionsSchema>, TImmutableDBKeys>
>;
