// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AgentVaultServiceVariableReferencesSchema = z.object({
  id: z.string().uuid(),
  serviceId: z.string().uuid(),
  variableId: z.string().uuid(),
  field: z.string(),
  customHeaderId: z.string().uuid().nullable().optional(),
  substitutionId: z.string().uuid().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAgentVaultServiceVariableReferences = z.infer<typeof AgentVaultServiceVariableReferencesSchema>;
export type TAgentVaultServiceVariableReferencesInsert = Omit<
  z.input<typeof AgentVaultServiceVariableReferencesSchema>,
  TImmutableDBKeys
>;
export type TAgentVaultServiceVariableReferencesUpdate = Partial<
  Omit<z.input<typeof AgentVaultServiceVariableReferencesSchema>, TImmutableDBKeys>
>;
