// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AgentGatewaySessionRequestsSchema = z.object({
  id: z.string().uuid(),
  sessionId: z.string().uuid(),
  occurredAt: z.date(),
  method: z.string(),
  host: z.string(),
  port: z.number().nullable().optional(),
  path: z.string().nullable().optional(),
  decision: z.string(),
  statusCode: z.number().nullable().optional(),
  serviceId: z.string().uuid().nullable().optional(),
  serviceName: z.string().nullable().optional(),
  credentials: z.unknown().nullable().optional(),
  errorMessage: z.string().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAgentGatewaySessionRequests = z.infer<typeof AgentGatewaySessionRequestsSchema>;
export type TAgentGatewaySessionRequestsInsert = Omit<
  z.input<typeof AgentGatewaySessionRequestsSchema>,
  TImmutableDBKeys
>;
export type TAgentGatewaySessionRequestsUpdate = Partial<
  Omit<z.input<typeof AgentGatewaySessionRequestsSchema>, TImmutableDBKeys>
>;
