// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AgentVaultProxiesSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  name: z.string(),
  tokenVersion: z.number().default(0),
  rootCaCertificate: z.string().nullable().optional(),
  rootCaFingerprint: z.string().nullable().optional(),
  rootCaExpiresAt: z.date().nullable().optional(),
  heartbeat: z.date().nullable().optional(),
  version: z.string().nullable().optional(),
  unmatchedHost: z.string().default("allow"),
  bypassHosts: z.string().nullable().optional(),
  pollInterval: z.number().default(60),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAgentVaultProxies = z.infer<typeof AgentVaultProxiesSchema>;
export type TAgentVaultProxiesInsert = Omit<z.input<typeof AgentVaultProxiesSchema>, TImmutableDBKeys>;
export type TAgentVaultProxiesUpdate = Partial<Omit<z.input<typeof AgentVaultProxiesSchema>, TImmutableDBKeys>>;
