// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AgentProxiesSchema = z.object({
  id: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  orgId: z.string().uuid(),
  name: z.string(),
  tokenVersion: z.number().default(0),
  heartbeat: z.date().nullable().optional(),
  healthAlertedAt: z.date().nullable().optional(),
  allowedHosts: z.string().array().nullable().optional()
});

export type TAgentProxies = z.infer<typeof AgentProxiesSchema>;
export type TAgentProxiesInsert = Omit<z.input<typeof AgentProxiesSchema>, TImmutableDBKeys>;
export type TAgentProxiesUpdate = Partial<Omit<z.input<typeof AgentProxiesSchema>, TImmutableDBKeys>>;
