// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AgentGatewaySessionsSchema = z.object({
  id: z.string().uuid(),
  agentGatewayId: z.string().uuid(),
  projectId: z.string(),
  gatewayId: z.string().uuid().nullable().optional(),
  mode: z.string(),
  status: z.string(),
  actorUserId: z.string().uuid().nullable().optional(),
  actorIdentityId: z.string().uuid().nullable().optional(),
  actorName: z.string(),
  expiresAt: z.date(),
  endedAt: z.date().nullable().optional(),
  lastResolvedAt: z.date().nullable().optional(),
  resolvedRefFingerprint: z.string().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAgentGatewaySessions = z.infer<typeof AgentGatewaySessionsSchema>;
export type TAgentGatewaySessionsInsert = Omit<z.input<typeof AgentGatewaySessionsSchema>, TImmutableDBKeys>;
export type TAgentGatewaySessionsUpdate = Partial<Omit<z.input<typeof AgentGatewaySessionsSchema>, TImmutableDBKeys>>;
