// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AgentVaultActivityChunksSchema = z.object({
  id: z.string().uuid(),
  chunkId: z.string(),
  sessionId: z.string().uuid(),
  projectId: z.string(),
  proxyId: z.string(),
  proxyName: z.string(),
  startedAt: z.date(),
  endedAt: z.date(),
  firstSeq: z.coerce.number(),
  lastSeq: z.coerce.number(),
  recordCount: z.number(),
  droppedCount: z.coerce.number().default(0),
  bucket: z.string(),
  objectKey: z.string(),
  ciphertextBytes: z.number(),
  iv: z.string(),
  ciphertextSha256: z.string(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAgentVaultActivityChunks = z.infer<typeof AgentVaultActivityChunksSchema>;
export type TAgentVaultActivityChunksInsert = Omit<z.input<typeof AgentVaultActivityChunksSchema>, TImmutableDBKeys>;
export type TAgentVaultActivityChunksUpdate = Partial<
  Omit<z.input<typeof AgentVaultActivityChunksSchema>, TImmutableDBKeys>
>;
