// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const AgentVaultServicesSchema = z.object({
  id: z.string().uuid(),
  accessBundleId: z.string().uuid(),
  name: z.string(),
  hostPattern: z.string(),
  credentialType: z.string(),
  credentialConfig: z.unknown(),
  encryptedCredential: zodBuffer.nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAgentVaultServices = z.infer<typeof AgentVaultServicesSchema>;
export type TAgentVaultServicesInsert = Omit<z.input<typeof AgentVaultServicesSchema>, TImmutableDBKeys>;
export type TAgentVaultServicesUpdate = Partial<Omit<z.input<typeof AgentVaultServicesSchema>, TImmutableDBKeys>>;
