// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AgentPolicyCredentialsSchema = z.object({
  id: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  policyId: z.string().uuid(),
  envId: z.string().uuid(),
  secretPath: z.string().default("/"),
  secretKey: z.string(),
  role: z.string(),
  headerName: z.string().nullable().optional(),
  headerPrefix: z.string().nullable().optional(),
  headerPurpose: z.string().nullable().optional(),
  placeholderKey: z.string().nullable().optional(),
  placeholderValue: z.string().nullable().optional(),
  substitutionSurfaces: z.string().array().nullable().optional()
});

export type TAgentPolicyCredentials = z.infer<typeof AgentPolicyCredentialsSchema>;
export type TAgentPolicyCredentialsInsert = Omit<z.input<typeof AgentPolicyCredentialsSchema>, TImmutableDBKeys>;
export type TAgentPolicyCredentialsUpdate = Partial<
  Omit<z.input<typeof AgentPolicyCredentialsSchema>, TImmutableDBKeys>
>;
