// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AiMcpEndpointServerToolsSchema = z.object({
  id: z.string().uuid(),
  aiMcpEndpointId: z.string().uuid(),
  aiMcpServerToolId: z.string().uuid(),
  isEnabled: z.boolean().default(false)
});

export type TAiMcpEndpointServerTools = z.infer<typeof AiMcpEndpointServerToolsSchema>;
export type TAiMcpEndpointServerToolsInsert = Omit<z.input<typeof AiMcpEndpointServerToolsSchema>, TImmutableDBKeys>;
export type TAiMcpEndpointServerToolsUpdate = Partial<
  Omit<z.input<typeof AiMcpEndpointServerToolsSchema>, TImmutableDBKeys>
>;
