// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AiMcpEndpointServersSchema = z.object({
  id: z.string().uuid(),
  aiMcpEndpointId: z.string().uuid(),
  aiMcpServerId: z.string().uuid()
});

export type TAiMcpEndpointServers = z.infer<typeof AiMcpEndpointServersSchema>;
export type TAiMcpEndpointServersInsert = Omit<z.input<typeof AiMcpEndpointServersSchema>, TImmutableDBKeys>;
export type TAiMcpEndpointServersUpdate = Partial<Omit<z.input<typeof AiMcpEndpointServersSchema>, TImmutableDBKeys>>;
