// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AlarmHistoryTargetSchema = z.object({
  id: z.string().uuid(),
  alarmHistoryId: z.string().uuid(),
  targetId: z.string(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAlarmHistoryTarget = z.infer<typeof AlarmHistoryTargetSchema>;
export type TAlarmHistoryTargetInsert = Omit<z.input<typeof AlarmHistoryTargetSchema>, TImmutableDBKeys>;
export type TAlarmHistoryTargetUpdate = Partial<Omit<z.input<typeof AlarmHistoryTargetSchema>, TImmutableDBKeys>>;
