// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AlarmChannelMembershipsSchema = z.object({
  id: z.string().uuid(),
  alarmId: z.string().uuid(),
  channelId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAlarmChannelMemberships = z.infer<typeof AlarmChannelMembershipsSchema>;
export type TAlarmChannelMembershipsInsert = Omit<z.input<typeof AlarmChannelMembershipsSchema>, TImmutableDBKeys>;
export type TAlarmChannelMembershipsUpdate = Partial<
  Omit<z.input<typeof AlarmChannelMembershipsSchema>, TImmutableDBKeys>
>;
