// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AlarmHistorySchema = z.object({
  id: z.string().uuid(),
  alarmId: z.string().uuid(),
  triggeredAt: z.date().nullable().optional(),
  status: z.string(),
  error: z.string().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAlarmHistory = z.infer<typeof AlarmHistorySchema>;
export type TAlarmHistoryInsert = Omit<z.input<typeof AlarmHistorySchema>, TImmutableDBKeys>;
export type TAlarmHistoryUpdate = Partial<Omit<z.input<typeof AlarmHistorySchema>, TImmutableDBKeys>>;
