// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AlertHistoryTargetSchema = z.object({
  id: z.string().uuid(),
  alertHistoryId: z.string().uuid(),
  targetId: z.string(),
  channelId: z.string().uuid().nullable().optional(),
  channelType: z.string(),
  status: z.string(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAlertHistoryTarget = z.infer<typeof AlertHistoryTargetSchema>;
export type TAlertHistoryTargetInsert = Omit<z.input<typeof AlertHistoryTargetSchema>, TImmutableDBKeys>;
export type TAlertHistoryTargetUpdate = Partial<Omit<z.input<typeof AlertHistoryTargetSchema>, TImmutableDBKeys>>;
