// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const AlertChannelsSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  channelType: z.string(),
  encryptedConfig: zodBuffer,
  enabled: z.boolean().default(true),
  orgId: z.string().uuid(),
  projectId: z.string().nullable().optional(),
  createdByUserId: z.string().uuid().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAlertChannels = z.infer<typeof AlertChannelsSchema>;
export type TAlertChannelsInsert = Omit<z.input<typeof AlertChannelsSchema>, TImmutableDBKeys>;
export type TAlertChannelsUpdate = Partial<Omit<z.input<typeof AlertChannelsSchema>, TImmutableDBKeys>>;
