// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ApprovalPoliciesSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  organizationId: z.string().uuid(),
  type: z.string(),
  name: z.string(),
  isActive: z.boolean().default(true).nullable().optional(),
  maxRequestTtl: z.string().nullable().optional(),
  conditions: z.unknown(),
  constraints: z.unknown(),
  createdAt: z.date(),
  updatedAt: z.date(),
  bypassForMachineIdentities: z.boolean().default(false)
});

export type TApprovalPolicies = z.infer<typeof ApprovalPoliciesSchema>;
export type TApprovalPoliciesInsert = Omit<z.input<typeof ApprovalPoliciesSchema>, TImmutableDBKeys>;
export type TApprovalPoliciesUpdate = Partial<Omit<z.input<typeof ApprovalPoliciesSchema>, TImmutableDBKeys>>;
