// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ApprovalPolicyStepsSchema = z.object({
  id: z.string().uuid(),
  policyId: z.string().uuid(),
  name: z.string().nullable().optional(),
  stepNumber: z.number(),
  requiredApprovals: z.number(),
  notifyApprovers: z.boolean().default(false).nullable().optional()
});

export type TApprovalPolicySteps = z.infer<typeof ApprovalPolicyStepsSchema>;
export type TApprovalPolicyStepsInsert = Omit<z.input<typeof ApprovalPolicyStepsSchema>, TImmutableDBKeys>;
export type TApprovalPolicyStepsUpdate = Partial<Omit<z.input<typeof ApprovalPolicyStepsSchema>, TImmutableDBKeys>>;
