// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ApprovalRequestsSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  organizationId: z.string().uuid(),
  policyId: z.string().uuid(),
  requesterId: z.string().uuid(),
  requesterName: z.string(),
  requesterEmail: z.string(),
  type: z.string(),
  status: z.string(),
  justification: z.string().nullable().optional(),
  currentStep: z.number(),
  requestData: z.unknown(),
  expiresAt: z.date().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TApprovalRequests = z.infer<typeof ApprovalRequestsSchema>;
export type TApprovalRequestsInsert = Omit<z.input<typeof ApprovalRequestsSchema>, TImmutableDBKeys>;
export type TApprovalRequestsUpdate = Partial<Omit<z.input<typeof ApprovalRequestsSchema>, TImmutableDBKeys>>;
