// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ApprovalRequestStepEligibleApproversSchema = z.object({
  id: z.string().guid(),
  stepId: z.string().guid(),
  userId: z.string().guid().nullable().optional(),
  groupId: z.string().guid().nullable().optional()
});

export type TApprovalRequestStepEligibleApprovers = z.infer<typeof ApprovalRequestStepEligibleApproversSchema>;
export type TApprovalRequestStepEligibleApproversInsert = Omit<
  z.input<typeof ApprovalRequestStepEligibleApproversSchema>,
  TImmutableDBKeys
>;
export type TApprovalRequestStepEligibleApproversUpdate = Partial<
  Omit<z.input<typeof ApprovalRequestStepEligibleApproversSchema>, TImmutableDBKeys>
>;
