// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AuditLogStreamsSchema = z.object({
  id: z.string().uuid(),
  url: z.string(),
  encryptedTokenCiphertext: z.string().nullable().optional(),
  encryptedTokenIV: z.string().nullable().optional(),
  encryptedTokenTag: z.string().nullable().optional(),
  encryptedTokenAlgorithm: z.string().nullable().optional(),
  encryptedTokenKeyEncoding: z.string().nullable().optional(),
  orgId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAuditLogStreams = z.infer<typeof AuditLogStreamsSchema>;
export type TAuditLogStreamsInsert = Omit<z.input<typeof AuditLogStreamsSchema>, TImmutableDBKeys>;
export type TAuditLogStreamsUpdate = Partial<Omit<z.input<typeof AuditLogStreamsSchema>, TImmutableDBKeys>>;
