// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const AuditLogStreamOutboxSchema = z.object({
  id: z.coerce.number(),
  streamId: z.string().uuid(),
  orgId: z.string().uuid(),
  auditLogId: z.string().uuid(),
  payload: z.unknown(),
  status: z.string().default("pending"),
  attempts: z.number().default(0),
  nextRetryAt: z.date(),
  lockedAt: z.date().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TAuditLogStreamOutbox = z.infer<typeof AuditLogStreamOutboxSchema>;
export type TAuditLogStreamOutboxInsert = Omit<z.input<typeof AuditLogStreamOutboxSchema>, TImmutableDBKeys>;
export type TAuditLogStreamOutboxUpdate = Partial<Omit<z.input<typeof AuditLogStreamOutboxSchema>, TImmutableDBKeys>>;
