// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "./utils/zod";

import { TImmutableDBKeys } from "./models";

export const CertificateTemplateEstConfigsSchema = z.object({
  id: z.string().uuid(),
  certificateTemplateId: z.string().uuid(),
  encryptedCaChain: zodBuffer.nullable().optional(),
  hashedPassphrase: z.string(),
  isEnabled: z.boolean(),
  createdAt: z.date(),
  updatedAt: z.date(),
  disableBootstrapCertValidation: z.boolean().default(false)
});

export type TCertificateTemplateEstConfigs = z.infer<typeof CertificateTemplateEstConfigsSchema>;
export type TCertificateTemplateEstConfigsInsert = Omit<
  z.input<typeof CertificateTemplateEstConfigsSchema>,
  TImmutableDBKeys
>;
export type TCertificateTemplateEstConfigsUpdate = Partial<
  Omit<z.input<typeof CertificateTemplateEstConfigsSchema>, TImmutableDBKeys>
>;
