// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const CertificateInventoryViewsSchema = z.object({
  id: z.string().guid(),
  projectId: z.string(),
  name: z.string(),
  filters: z.unknown(),
  columns: z.unknown().nullable().optional(),
  createdByUserId: z.string().guid().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date(),
  isShared: z.boolean().default(false),
  applicationId: z.string().guid().nullable().optional()
});

export type TCertificateInventoryViews = z.infer<typeof CertificateInventoryViewsSchema>;
export type TCertificateInventoryViewsInsert = Omit<z.input<typeof CertificateInventoryViewsSchema>, TImmutableDBKeys>;
export type TCertificateInventoryViewsUpdate = Partial<
  Omit<z.input<typeof CertificateInventoryViewsSchema>, TImmutableDBKeys>
>;
