// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const CertificateTemplatesV2Schema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  name: z.string(),
  description: z.string().nullable().optional(),
  subject: z.unknown().nullable().optional(),
  sans: z.unknown().nullable().optional(),
  keyUsages: z.unknown().nullable().optional(),
  extendedKeyUsages: z.unknown().nullable().optional(),
  algorithms: z.unknown().nullable().optional(),
  validity: z.unknown().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TCertificateTemplatesV2 = z.infer<typeof CertificateTemplatesV2Schema>;
export type TCertificateTemplatesV2Insert = Omit<z.input<typeof CertificateTemplatesV2Schema>, TImmutableDBKeys>;
export type TCertificateTemplatesV2Update = Partial<
  Omit<z.input<typeof CertificateTemplatesV2Schema>, TImmutableDBKeys>
>;
