// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const ConsumerSecretsKmsRootConfigSchema = z.object({
  id: z.string().uuid(),
  encryptedRootKey: zodBuffer
});

export type TConsumerSecretsKmsRootConfig = z.infer<typeof ConsumerSecretsKmsRootConfigSchema>;
export type TConsumerSecretsKmsRootConfigInsert = Omit<
  z.input<typeof ConsumerSecretsKmsRootConfigSchema>,
  TImmutableDBKeys
>;
export type TConsumerSecretsKmsRootConfigUpdate = Partial<
  Omit<z.input<typeof ConsumerSecretsKmsRootConfigSchema>, TImmutableDBKeys>
>;
