// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ConversationsSchema = z.object({
  id: z.string().uuid(),
  organizationId: z.string(),
  userId: z.string(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TConversations = z.infer<typeof ConversationsSchema>;
export type TConversationsInsert = Omit<z.input<typeof ConversationsSchema>, TImmutableDBKeys>;
export type TConversationsUpdate = Partial<Omit<z.input<typeof ConversationsSchema>, TImmutableDBKeys>>;
