// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const CredentialSecureNotesSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  credentialId: z.string().uuid().default("00000000-0000-0000-0000-000000000000"),
  userId: z.string().uuid(),
  orgId: z.string().uuid(),
  encryptedNote: z.string(),
  encryptedNoteIV: z.string(),
  encryptedNoteTag: z.string()
});

export type TCredentialSecureNotes = z.infer<typeof CredentialSecureNotesSchema>;
export type TCredentialSecureNotesInsert = Omit<z.input<typeof CredentialSecureNotesSchema>, TImmutableDBKeys>;
export type TCredentialSecureNotesUpdate = Partial<Omit<z.input<typeof CredentialSecureNotesSchema>, TImmutableDBKeys>>;
