// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const DedicatedInstancesSchema = z.object({
  id: z.string().uuid(),
  orgId: z.string().uuid(),
  instanceName: z.string(),
  status: z.string(),
  rdsInstanceType: z.string(),
  elasticCacheType: z.string(),
  elasticContainerMemory: z.number(),
  elasticContainerCpu: z.number(),
  region: z.string(),
  version: z.string(),
  backupRetentionDays: z.number().default(7).nullable().optional(),
  lastBackupTime: z.date().nullable().optional(),
  lastUpgradeTime: z.date().nullable().optional(),
  publiclyAccessible: z.boolean().default(false).nullable().optional(),
  vpcId: z.string().nullable().optional(),
  subnetIds: z.string().array().nullable().optional(),
  tags: z.unknown().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TDedicatedInstances = z.infer<typeof DedicatedInstancesSchema>;
export type TDedicatedInstancesInsert = Omit<z.input<typeof DedicatedInstancesSchema>, TImmutableDBKeys>;
export type TDedicatedInstancesUpdate = Partial<Omit<z.input<typeof DedicatedInstancesSchema>, TImmutableDBKeys>>;
