// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const EndpointSecretFindingsSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  deviceId: z.string().uuid(),
  fingerprint: z.string(),
  ruleId: z.string(),
  description: z.string().nullable().optional(),
  file: z.string(),
  startLine: z.number(),
  entropy: z.number().nullable().optional(),
  redactedMatch: z.string().nullable().optional(),
  fileModifiedAt: z.date().nullable().optional(),
  status: z.string().default("open"),
  firstSeenAt: z.date(),
  lastSeenAt: z.date(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TEndpointSecretFindings = z.infer<typeof EndpointSecretFindingsSchema>;
export type TEndpointSecretFindingsInsert = Omit<z.input<typeof EndpointSecretFindingsSchema>, TImmutableDBKeys>;
export type TEndpointSecretFindingsUpdate = Partial<
  Omit<z.input<typeof EndpointSecretFindingsSchema>, TImmutableDBKeys>
>;
