// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";



import { TImmutableDBKeys } from "./models";

export const EndpointScanPoliciesSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  isEnabled: z.boolean().default(false),
  roots: z.unknown(),
  excludePatterns: z.unknown().nullable().optional(),
  maxFileMegabytes: z.number().nullable().optional(),
  intervalHours: z.number().default(24),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TEndpointScanPolicies = z.infer<typeof EndpointScanPoliciesSchema>;
export type TEndpointScanPoliciesInsert = Omit<z.input<typeof EndpointScanPoliciesSchema>, TImmutableDBKeys>;
export type TEndpointScanPoliciesUpdate = Partial<Omit<z.input<typeof EndpointScanPoliciesSchema>, TImmutableDBKeys>>;
