// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const EndpointEventsSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  deviceId: z.string().uuid(),
  eventType: z.string(),
  occurredAt: z.date(),
  destination: z.string().nullable().optional(),
  egressRuleId: z.string().uuid().nullable().optional(),
  detail: z.unknown().nullable().optional(),
  idempotencyKey: z.string(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TEndpointEvents = z.infer<typeof EndpointEventsSchema>;
export type TEndpointEventsInsert = Omit<z.input<typeof EndpointEventsSchema>, TImmutableDBKeys>;
export type TEndpointEventsUpdate = Partial<Omit<z.input<typeof EndpointEventsSchema>, TImmutableDBKeys>>;
