// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const EndpointTransferBucketsSchema = z.object({
  id: z.string().uuid(),
  deviceId: z.string().uuid(),
  destination: z.string(),
  bucketStartedAt: z.date(),
  bytesOut: z.coerce.number().default(0),
  firstSeenAt: z.date(),
  lastSeenAt: z.date(),
  blocked: z.boolean().default(false),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TEndpointTransferBuckets = z.infer<typeof EndpointTransferBucketsSchema>;
export type TEndpointTransferBucketsInsert = Omit<z.input<typeof EndpointTransferBucketsSchema>, TImmutableDBKeys>;
export type TEndpointTransferBucketsUpdate = Partial<
  Omit<z.input<typeof EndpointTransferBucketsSchema>, TImmutableDBKeys>
>;
