// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const EndpointEgressRulesSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  ruleType: z.string(),
  action: z.string().nullable().optional(),
  kind: z.string(),
  destination: z.string(),
  thresholdBytes: z.coerce.number().nullable().optional(),
  name: z.string(),
  isEnabled: z.boolean().default(true),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TEndpointEgressRules = z.infer<typeof EndpointEgressRulesSchema>;
export type TEndpointEgressRulesInsert = Omit<z.input<typeof EndpointEgressRulesSchema>, TImmutableDBKeys>;
export type TEndpointEgressRulesUpdate = Partial<Omit<z.input<typeof EndpointEgressRulesSchema>, TImmutableDBKeys>>;
