// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const EndpointTargetsSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  name: z.string(),
  kind: z.string(),
  destination: z.string(),
  ip: z.string().nullable().optional(),
  port: z.number(),
  loopbackIp: z.string().nullable().optional(),
  gatewayId: z.string().uuid().nullable().optional(),
  isEnabled: z.boolean().default(true),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TEndpointTargets = z.infer<typeof EndpointTargetsSchema>;
export type TEndpointTargetsInsert = Omit<z.input<typeof EndpointTargetsSchema>, TImmutableDBKeys>;
export type TEndpointTargetsUpdate = Partial<Omit<z.input<typeof EndpointTargetsSchema>, TImmutableDBKeys>>;
