// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const ExternalConsumerSecretsKmsSchema = z.object({
  id: z.string().uuid(),
  provider: z.string(),
  encryptedProviderInputs: zodBuffer,
  status: z.string().nullable().optional(),
  statusDetails: z.string().nullable().optional(),
  kmsKeyId: z.string().uuid()
});

export type TExternalConsumerSecretsKms = z.infer<typeof ExternalConsumerSecretsKmsSchema>;
export type TExternalConsumerSecretsKmsInsert = Omit<
  z.input<typeof ExternalConsumerSecretsKmsSchema>,
  TImmutableDBKeys
>;
export type TExternalConsumerSecretsKmsUpdate = Partial<
  Omit<z.input<typeof ExternalConsumerSecretsKmsSchema>, TImmutableDBKeys>
>;
