// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const ExternalMigrationConfigsSchema = z.object({
  id: z.string().guid(),
  orgId: z.string().guid(),
  provider: z.string(),
  encryptedConfig: zodBuffer,
  connectionId: z.string().guid().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TExternalMigrationConfigs = z.infer<typeof ExternalMigrationConfigsSchema>;
export type TExternalMigrationConfigsInsert = Omit<z.input<typeof ExternalMigrationConfigsSchema>, TImmutableDBKeys>;
export type TExternalMigrationConfigsUpdate = Partial<
  Omit<z.input<typeof ExternalMigrationConfigsSchema>, TImmutableDBKeys>
>;
