// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const FolderCommitsSchema = z.object({
  id: z.coerce.number(),
  actorName: z.string(),
  actorType: z.string(),
  message: z.string().nullable().optional(),
  date: z.date(),
  folderId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TFolderCommits = z.infer<typeof FolderCommitsSchema>;
export type TFolderCommitsInsert = Omit<z.input<typeof FolderCommitsSchema>, TImmutableDBKeys>;
export type TFolderCommitsUpdate = Partial<Omit<z.input<typeof FolderCommitsSchema>, TImmutableDBKeys>>;
