// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const FolderTreeCheckpointResourcesSchema = z.object({
  id: z.string().uuid(),
  folderTreeCheckpointId: z.string().uuid(),
  folderId: z.string().uuid(),
  folderCommitId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TFolderTreeCheckpointResources = z.infer<typeof FolderTreeCheckpointResourcesSchema>;
export type TFolderTreeCheckpointResourcesInsert = Omit<
  z.input<typeof FolderTreeCheckpointResourcesSchema>,
  TImmutableDBKeys
>;
export type TFolderTreeCheckpointResourcesUpdate = Partial<
  Omit<z.input<typeof FolderTreeCheckpointResourcesSchema>, TImmutableDBKeys>
>;
