// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const FolderCommitChangesSchema = z.object({
  id: z.string().guid(),
  folderCommitId: z.string().guid(),
  changeType: z.string(),
  isUpdate: z.boolean().default(false),
  secretVersionId: z.string().guid().nullable().optional(),
  folderVersionId: z.string().guid().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TFolderCommitChanges = z.infer<typeof FolderCommitChangesSchema>;
export type TFolderCommitChangesInsert = Omit<z.input<typeof FolderCommitChangesSchema>, TImmutableDBKeys>;
export type TFolderCommitChangesUpdate = Partial<Omit<z.input<typeof FolderCommitChangesSchema>, TImmutableDBKeys>>;
