// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const GatewayEnrollmentTokensSchema = z.object({
  id: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  orgId: z.string().uuid(),
  name: z.string(),
  tokenHash: z.string(),
  ttl: z.number().int(),
  expiresAt: z.date(),
  usedAt: z.date().nullable().optional(),
  gatewayId: z.string().uuid().nullable().optional()
});

export type TGatewayEnrollmentTokens = z.infer<typeof GatewayEnrollmentTokensSchema>;
export type TGatewayEnrollmentTokensInsert = Omit<z.input<typeof GatewayEnrollmentTokensSchema>, TImmutableDBKeys>;
export type TGatewayEnrollmentTokensUpdate = Partial<
  Omit<z.input<typeof GatewayEnrollmentTokensSchema>, TImmutableDBKeys>
>;
