// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "./utils/zod";

import { TImmutableDBKeys } from "./models";

export const GatewaysV2Schema = z.object({
  id: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  orgId: z.string().uuid(),
  identityId: z.string().uuid(),
  relayId: z.string().uuid().nullable().optional(),
  name: z.string(),
  heartbeat: z.date().nullable().optional(),
  encryptedPamSessionKey: zodBuffer.nullable().optional(),
  healthAlertedAt: z.date().nullable().optional()
});

export type TGatewaysV2 = z.infer<typeof GatewaysV2Schema>;
export type TGatewaysV2Insert = Omit<z.input<typeof GatewaysV2Schema>, TImmutableDBKeys>;
export type TGatewaysV2Update = Partial<Omit<z.input<typeof GatewaysV2Schema>, TImmutableDBKeys>>;
