// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const GithubAppsSchema = z.object({
  id: z.string().uuid(),
  orgId: z.string().uuid(),
  name: z.string(),
  appId: z.string(),
  clientId: z.string(),
  encryptedClientSecret: zodBuffer,
  encryptedPrivateKey: zodBuffer,
  slug: z.string(),
  owner: z.string().nullable().optional(),
  host: z.string().nullable().optional(),
  instanceType: z.string().default("cloud"),
  projectId: z.string().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TGithubApps = z.infer<typeof GithubAppsSchema>;
export type TGithubAppsInsert = Omit<z.input<typeof GithubAppsSchema>, TImmutableDBKeys>;
export type TGithubAppsUpdate = Partial<Omit<z.input<typeof GithubAppsSchema>, TImmutableDBKeys>>;
