// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const HoneyTokenSecretMappingsSchema = z.object({
  id: z.string().uuid(),
  secretId: z.string().uuid(),
  honeyTokenId: z.string().uuid()
});

export type THoneyTokenSecretMappings = z.infer<typeof HoneyTokenSecretMappingsSchema>;
export type THoneyTokenSecretMappingsInsert = Omit<z.input<typeof HoneyTokenSecretMappingsSchema>, TImmutableDBKeys>;
export type THoneyTokenSecretMappingsUpdate = Partial<
  Omit<z.input<typeof HoneyTokenSecretMappingsSchema>, TImmutableDBKeys>
>;
