// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const IdentityAuthTemplatesSchema = z.object({
  id: z.string().guid(),
  templateFields: zodBuffer,
  orgId: z.string().guid(),
  name: z.string(),
  authMethod: z.string(),
  createdAt: z.date(),
  updatedAt: z.date(),
  gatewayId: z.string().guid().nullable().optional(),
  gatewayV2Id: z.string().guid().nullable().optional(),
  gatewayPoolId: z.string().guid().nullable().optional()
});

export type TIdentityAuthTemplates = z.infer<typeof IdentityAuthTemplatesSchema>;
export type TIdentityAuthTemplatesInsert = Omit<z.input<typeof IdentityAuthTemplatesSchema>, TImmutableDBKeys>;
export type TIdentityAuthTemplatesUpdate = Partial<Omit<z.input<typeof IdentityAuthTemplatesSchema>, TImmutableDBKeys>>;
