// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const IdentityAccessTokenRevocationsSchema = z.object({
  id: z.string().uuid(),
  identityId: z.string().uuid(),
  expiresAt: z.date(),
  revokedAt: z.date().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TIdentityAccessTokenRevocations = z.infer<typeof IdentityAccessTokenRevocationsSchema>;
export type TIdentityAccessTokenRevocationsInsert = Omit<
  z.input<typeof IdentityAccessTokenRevocationsSchema>,
  TImmutableDBKeys
>;
export type TIdentityAccessTokenRevocationsUpdate = Partial<
  Omit<z.input<typeof IdentityAccessTokenRevocationsSchema>, TImmutableDBKeys>
>;
