// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const IdentityGroupMembershipSchema = z.object({
  id: z.string().uuid(),
  identityId: z.string().uuid(),
  groupId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TIdentityGroupMembership = z.infer<typeof IdentityGroupMembershipSchema>;
export type TIdentityGroupMembershipInsert = Omit<z.input<typeof IdentityGroupMembershipSchema>, TImmutableDBKeys>;
export type TIdentityGroupMembershipUpdate = Partial<
  Omit<z.input<typeof IdentityGroupMembershipSchema>, TImmutableDBKeys>
>;
