// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const IdentityMetadataSchema = z.object({
  id: z.string().guid(),
  key: z.string(),
  value: z.string(),
  orgId: z.string().guid(),
  userId: z.string().guid().nullable().optional(),
  identityId: z.string().guid().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TIdentityMetadata = z.infer<typeof IdentityMetadataSchema>;
export type TIdentityMetadataInsert = Omit<z.input<typeof IdentityMetadataSchema>, TImmutableDBKeys>;
export type TIdentityMetadataUpdate = Partial<Omit<z.input<typeof IdentityMetadataSchema>, TImmutableDBKeys>>;
