// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const IdentitySpiffeAuthsSchema = z.object({
  id: z.string().uuid(),
  identityId: z.string().uuid(),
  trustDomain: z.string(),
  allowedSpiffeIds: z.string(),
  allowedAudiences: z.string(),
  configurationType: z.string(),
  encryptedCaBundleJwks: zodBuffer.nullable().optional(),
  bundleEndpointUrl: z.string().nullable().optional(),
  bundleEndpointProfile: z.string().nullable().optional(),
  encryptedBundleEndpointCaCert: zodBuffer.nullable().optional(),
  encryptedCachedBundleJwks: zodBuffer.nullable().optional(),
  cachedBundleLastRefreshedAt: z.date().nullable().optional(),
  bundleRefreshHintSeconds: z.coerce.number().default(300),
  accessTokenTTL: z.coerce.number().default(7200),
  accessTokenMaxTTL: z.coerce.number().default(7200),
  accessTokenNumUsesLimit: z.coerce.number().default(0),
  accessTokenTrustedIps: z.unknown(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TIdentitySpiffeAuths = z.infer<typeof IdentitySpiffeAuthsSchema>;
export type TIdentitySpiffeAuthsInsert = Omit<z.input<typeof IdentitySpiffeAuthsSchema>, TImmutableDBKeys>;
export type TIdentitySpiffeAuthsUpdate = Partial<Omit<z.input<typeof IdentitySpiffeAuthsSchema>, TImmutableDBKeys>>;
