// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const InfraVariablesSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  key: z.string(),
  value: z.string().default(""),
  sensitive: z.boolean().default(false),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TInfraVariables = z.infer<typeof InfraVariablesSchema>;
export type TInfraVariablesInsert = Omit<z.input<typeof InfraVariablesSchema>, TImmutableDBKeys>;
export type TInfraVariablesUpdate = Partial<Omit<z.input<typeof InfraVariablesSchema>, TImmutableDBKeys>>;
