// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "./utils/zod";

import { TImmutableDBKeys } from "./models";

export const InstanceRelayConfigSchema = z.object({
  id: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  encryptedRootRelayPkiCaPrivateKey: zodBuffer,
  encryptedRootRelayPkiCaCertificate: zodBuffer,
  encryptedInstanceRelayPkiCaPrivateKey: zodBuffer,
  encryptedInstanceRelayPkiCaCertificate: zodBuffer,
  encryptedInstanceRelayPkiCaCertificateChain: zodBuffer,
  encryptedInstanceRelayPkiClientCaPrivateKey: zodBuffer,
  encryptedInstanceRelayPkiClientCaCertificate: zodBuffer,
  encryptedInstanceRelayPkiClientCaCertificateChain: zodBuffer,
  encryptedInstanceRelayPkiServerCaPrivateKey: zodBuffer,
  encryptedInstanceRelayPkiServerCaCertificate: zodBuffer,
  encryptedInstanceRelayPkiServerCaCertificateChain: zodBuffer,
  encryptedOrgRelayPkiCaPrivateKey: zodBuffer,
  encryptedOrgRelayPkiCaCertificate: zodBuffer,
  encryptedOrgRelayPkiCaCertificateChain: zodBuffer,
  encryptedInstanceRelaySshClientCaPrivateKey: zodBuffer,
  encryptedInstanceRelaySshClientCaPublicKey: zodBuffer,
  encryptedInstanceRelaySshServerCaPrivateKey: zodBuffer,
  encryptedInstanceRelaySshServerCaPublicKey: zodBuffer
});

export type TInstanceRelayConfig = z.infer<typeof InstanceRelayConfigSchema>;
export type TInstanceRelayConfigInsert = Omit<z.input<typeof InstanceRelayConfigSchema>, TImmutableDBKeys>;
export type TInstanceRelayConfigUpdate = Partial<Omit<z.input<typeof InstanceRelayConfigSchema>, TImmutableDBKeys>>;
