// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const InternalConsumerSecretsKmsKeyVersionSchema = z.object({
  id: z.string().uuid(),
  encryptedKey: zodBuffer,
  version: z.number(),
  internalKmsId: z.string().uuid()
});

export type TInternalConsumerSecretsKmsKeyVersion = z.infer<typeof InternalConsumerSecretsKmsKeyVersionSchema>;
export type TInternalConsumerSecretsKmsKeyVersionInsert = Omit<
  z.input<typeof InternalConsumerSecretsKmsKeyVersionSchema>,
  TImmutableDBKeys
>;
export type TInternalConsumerSecretsKmsKeyVersionUpdate = Partial<
  Omit<z.input<typeof InternalConsumerSecretsKmsKeyVersionSchema>, TImmutableDBKeys>
>;
