// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const InternalKmsSchema = z.object({
  id: z.string().uuid(),
  encryptedKey: zodBuffer,
  encryptionAlgorithm: z.string(),
  version: z.number().default(1),
  kmsKeyId: z.string().uuid(),
  rotatedAt: z.date().nullable().optional(),
  rotationInterval: z.number().nullable().optional(),
  nextRotationAt: z.date().nullable().optional(),
  isAutoRotationEnabled: z.boolean().default(false),
  // Rotation status tracking
  lastRotationStatus: z.string().nullable().optional(),
  lastRotationAttemptedAt: z.date().nullable().optional(),
  lastRotationJobId: z.string().nullable().optional(),
  encryptedLastRotationMessage: zodBuffer.nullable().optional(),
  isLastRotationManual: z.boolean().nullable().optional()
});

export type TInternalKms = z.infer<typeof InternalKmsSchema>;
export type TInternalKmsInsert = Omit<z.input<typeof InternalKmsSchema>, TImmutableDBKeys>;
export type TInternalKmsUpdate = Partial<Omit<z.input<typeof InternalKmsSchema>, TImmutableDBKeys>>;
