// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const KmipServersSchema = z.object({
  id: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  orgId: z.string().uuid(),
  name: z.string(),
  heartbeat: z.date().nullable().optional(),
  tokenVersion: z.number().default(0)
});

export type TKmipServers = z.infer<typeof KmipServersSchema>;
export type TKmipServersInsert = Omit<z.input<typeof KmipServersSchema>, TImmutableDBKeys>;
export type TKmipServersUpdate = Partial<Omit<z.input<typeof KmipServersSchema>, TImmutableDBKeys>>;
