// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const KmsKeyImportMetaSchema = z.object({
  id: z.string().uuid(),
  keyId: z.string().uuid(),
  encryptionAlgorithm: z.string(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TKmsKeyImportMeta = z.infer<typeof KmsKeyImportMetaSchema>;
export type TKmsKeyImportMetaInsert = Omit<z.input<typeof KmsKeyImportMetaSchema>, TImmutableDBKeys>;
export type TKmsKeyImportMetaUpdate = Partial<Omit<z.input<typeof KmsKeyImportMetaSchema>, TImmutableDBKeys>>;
