// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "./utils/zod";

import { TImmutableDBKeys } from "./models";

export const LdapConfigsSchema = z.object({
  id: z.string().uuid(),
  orgId: z.string().uuid(),
  isActive: z.boolean(),
  url: z.string(),
  encryptedBindDN: z.string().nullable().optional(),
  bindDNIV: z.string().nullable().optional(),
  bindDNTag: z.string().nullable().optional(),
  encryptedBindPass: z.string().nullable().optional(),
  bindPassIV: z.string().nullable().optional(),
  bindPassTag: z.string().nullable().optional(),
  searchBase: z.string(),
  encryptedCACert: z.string().nullable().optional(),
  caCertIV: z.string().nullable().optional(),
  caCertTag: z.string().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date(),
  groupSearchBase: z.string().default(""),
  groupSearchFilter: z.string().default(""),
  searchFilter: z.string().default(""),
  uniqueUserAttribute: z.string().default(""),
  encryptedLdapBindDN: zodBuffer,
  encryptedLdapBindPass: zodBuffer,
  encryptedLdapCaCertificate: zodBuffer.nullable().optional()
});

export type TLdapConfigs = z.infer<typeof LdapConfigsSchema>;
export type TLdapConfigsInsert = Omit<z.input<typeof LdapConfigsSchema>, TImmutableDBKeys>;
export type TLdapConfigsUpdate = Partial<Omit<z.input<typeof LdapConfigsSchema>, TImmutableDBKeys>>;
