// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const NamespaceAdditionalPrivilegesSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  namespaceMembershipId: z.string().uuid(),
  isTemporary: z.boolean().default(false),
  temporaryMode: z.string().nullable().optional(),
  temporaryRange: z.string().nullable().optional(),
  temporaryAccessStartTime: z.date().nullable().optional(),
  temporaryAccessEndTime: z.date().nullable().optional(),
  permissions: z.unknown(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TNamespaceAdditionalPrivileges = z.infer<typeof NamespaceAdditionalPrivilegesSchema>;
export type TNamespaceAdditionalPrivilegesInsert = Omit<
  z.input<typeof NamespaceAdditionalPrivilegesSchema>,
  TImmutableDBKeys
>;
export type TNamespaceAdditionalPrivilegesUpdate = Partial<
  Omit<z.input<typeof NamespaceAdditionalPrivilegesSchema>, TImmutableDBKeys>
>;
