// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const NamespaceMembershipRolesSchema = z.object({
  id: z.string().uuid(),
  role: z.string(),
  customRoleId: z.string().uuid().nullable().optional(),
  isTemporary: z.boolean().default(false),
  temporaryMode: z.string().nullable().optional(),
  temporaryRange: z.string().nullable().optional(),
  temporaryAccessStartTime: z.date().nullable().optional(),
  temporaryAccessEndTime: z.date().nullable().optional(),
  namespaceMembershipId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TNamespaceMembershipRoles = z.infer<typeof NamespaceMembershipRolesSchema>;
export type TNamespaceMembershipRolesInsert = Omit<z.input<typeof NamespaceMembershipRolesSchema>, TImmutableDBKeys>;
export type TNamespaceMembershipRolesUpdate = Partial<
  Omit<z.input<typeof NamespaceMembershipRolesSchema>, TImmutableDBKeys>
>;
