// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const NhiIdentitiesSchema = z.object({
  id: z.string().uuid(),
  sourceId: z.string().uuid(),
  projectId: z.string(),
  externalId: z.string(),
  name: z.string(),
  type: z.string(),
  provider: z.string(),
  metadata: z.unknown(),
  riskScore: z.number().default(0),
  riskFactors: z.unknown().default("[]"),
  ownerEmail: z.string().nullable().optional(),
  status: z.string().default("active"),
  lastActivityAt: z.date().nullable().optional(),
  lastSeenAt: z.date(),
  riskAcceptedAt: z.date().nullable().optional(),
  riskAcceptedByUserId: z.string().uuid().nullable().optional(),
  riskAcceptedReason: z.string().nullable().optional(),
  riskAcceptedExpiresAt: z.date().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TNhiIdentities = z.infer<typeof NhiIdentitiesSchema>;
export type TNhiIdentitiesInsert = Omit<z.input<typeof NhiIdentitiesSchema>, TImmutableDBKeys>;
export type TNhiIdentitiesUpdate = Partial<Omit<z.input<typeof NhiIdentitiesSchema>, TImmutableDBKeys>>;
