// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const OrgGatewayRootCaSchema = z.object({
  id: z.string().uuid(),
  caKeyAlgorithm: z.string(),
  caSerialNumber: z.string(),
  caIssuedAt: z.date(),
  caExpiration: z.date(),
  encryptedCaCertificate: zodBuffer,
  encryptedCaPrivateKey: zodBuffer,
  orgId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TOrgGatewayRootCa = z.infer<typeof OrgGatewayRootCaSchema>;
export type TOrgGatewayRootCaInsert = Omit<z.input<typeof OrgGatewayRootCaSchema>, TImmutableDBKeys>;
export type TOrgGatewayRootCaUpdate = Partial<Omit<z.input<typeof OrgGatewayRootCaSchema>, TImmutableDBKeys>>;
