// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const OrganizationsSchema = z.object({
  id: z.string().guid(),
  name: z.string(),
  customerId: z.string().nullable().optional(),
  slug: z.string(),
  createdAt: z.date(),
  updatedAt: z.date(),
  authEnforced: z.boolean().nullable().optional(),
  scimEnabled: z.boolean().nullable().optional(),
  kmsDefaultKeyId: z.string().guid().nullable().optional(),
  kmsEncryptedDataKey: zodBuffer.nullable().optional(),
  defaultMembershipRole: z.string().default("member"),
  enforceMfa: z.boolean().default(false),
  selectedMfaMethod: z.string().nullable().optional(),
  allowSecretSharingOutsideOrganization: z.boolean().nullable().optional(),
  shouldUseNewPrivilegeSystem: z.boolean().default(true),
  privilegeUpgradeInitiatedByUsername: z.string().nullable().optional(),
  privilegeUpgradeInitiatedAt: z.date().nullable().optional(),
  bypassOrgAuthEnabled: z.boolean().default(false),
  userTokenExpiration: z.string().nullable().optional(),
  secretsProductEnabled: z.boolean().nullable().optional(),
  pkiProductEnabled: z.boolean().nullable().optional(),
  kmsProductEnabled: z.boolean().nullable().optional(),
  scannerProductEnabled: z.boolean().nullable().optional(),
  shareSecretsProductEnabled: z.boolean().nullable().optional(),
  maxSharedSecretLifetime: z.number().nullable().optional(),
  maxSharedSecretViewLimit: z.number().nullable().optional(),
  googleSsoAuthEnforced: z.boolean().default(false),
  googleSsoAuthLastUsed: z.date().nullable().optional(),
  parentOrgId: z.string().guid().nullable().optional(),
  rootOrgId: z.string().guid().nullable().optional(),
  blockDuplicateSecretSyncDestinations: z.boolean().default(false),
  secretShareBrandConfig: z.unknown().nullable().optional(),
  defaultCertManagerProjectId: z.string().nullable().optional(),
  allowCrossProjectSecretSharing: z.boolean().default(false),
  createdByUserId: z.string().guid().nullable().optional()
});

export type TOrganizations = z.infer<typeof OrganizationsSchema>;
export type TOrganizationsInsert = Omit<z.input<typeof OrganizationsSchema>, TImmutableDBKeys>;
export type TOrganizationsUpdate = Partial<Omit<z.input<typeof OrganizationsSchema>, TImmutableDBKeys>>;
