// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const PamResourcesSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  name: z.string(),
  gatewayId: z.string().uuid().nullable().optional(),
  resourceType: z.string(),
  encryptedConnectionDetails: zodBuffer,
  createdAt: z.date(),
  updatedAt: z.date(),
  encryptedRotationAccountCredentials: zodBuffer.nullable().optional()
});

export type TPamResources = z.infer<typeof PamResourcesSchema>;
export type TPamResourcesInsert = Omit<z.input<typeof PamResourcesSchema>, TImmutableDBKeys>;
export type TPamResourcesUpdate = Partial<Omit<z.input<typeof PamResourcesSchema>, TImmutableDBKeys>>;
