// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const PamSessionsSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  accountId: z.string().uuid().nullable().optional(),
  resourceType: z.string(),
  resourceName: z.string(),
  accountName: z.string(),
  userId: z.string().uuid().nullable().optional(),
  actorName: z.string(),
  actorEmail: z.string(),
  actorIp: z.string(),
  actorUserAgent: z.string(),
  status: z.string(),
  encryptedLogsBlob: zodBuffer.nullable().optional(),
  expiresAt: z.date(),
  startedAt: z.date().nullable().optional(),
  endedAt: z.date().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date(),
  accessMethod: z.string().nullable().optional()
});

export type TPamSessions = z.infer<typeof PamSessionsSchema>;
export type TPamSessionsInsert = Omit<z.input<typeof PamSessionsSchema>, TImmutableDBKeys>;
export type TPamSessionsUpdate = Partial<Omit<z.input<typeof PamSessionsSchema>, TImmutableDBKeys>>;
