// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PamDiscoveryRunsSchema = z.object({
  id: z.string().uuid(),
  discoverySourceId: z.string().uuid(),
  status: z.string(),
  triggeredBy: z.string(),
  resourcesDiscovered: z.number().default(0).nullable().optional(),
  accountsDiscovered: z.number().default(0).nullable().optional(),
  dependenciesDiscovered: z.number().default(0).nullable().optional(),
  newSinceLastRun: z.number().default(0).nullable().optional(),
  staleSinceLastRun: z.number().default(0).nullable().optional(),
  progress: z.unknown(),
  errorMessage: z.string().nullable().optional(),
  startedAt: z.date().nullable().optional(),
  completedAt: z.date().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPamDiscoveryRuns = z.infer<typeof PamDiscoveryRunsSchema>;
export type TPamDiscoveryRunsInsert = Omit<z.input<typeof PamDiscoveryRunsSchema>, TImmutableDBKeys>;
export type TPamDiscoveryRunsUpdate = Partial<Omit<z.input<typeof PamDiscoveryRunsSchema>, TImmutableDBKeys>>;
