// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PamFolderNotificationConfigsSchema = z.object({
  id: z.string().uuid(),
  folderId: z.string().uuid(),
  workflowIntegrationId: z.string().uuid(),
  channels: z.unknown(),
  events: z.unknown(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPamFolderNotificationConfigs = z.infer<typeof PamFolderNotificationConfigsSchema>;
export type TPamFolderNotificationConfigsInsert = Omit<
  z.input<typeof PamFolderNotificationConfigsSchema>,
  TImmutableDBKeys
>;
export type TPamFolderNotificationConfigsUpdate = Partial<
  Omit<z.input<typeof PamFolderNotificationConfigsSchema>, TImmutableDBKeys>
>;
