// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PamResourceFavoritesSchema = z.object({
  id: z.string().guid(),
  userId: z.string().guid(),
  pamResourceId: z.string().guid(),
  projectId: z.string(),
  createdAt: z.date().nullable().optional()
});

export type TPamResourceFavorites = z.infer<typeof PamResourceFavoritesSchema>;
export type TPamResourceFavoritesInsert = Omit<z.input<typeof PamResourceFavoritesSchema>, TImmutableDBKeys>;
export type TPamResourceFavoritesUpdate = Partial<Omit<z.input<typeof PamResourceFavoritesSchema>, TImmutableDBKeys>>;
