// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const PamAccountsSchema = z.object({
  id: z.string().uuid(),
  folderId: z.string().uuid().nullable().optional(),
  name: z.string(),
  description: z.string().nullable().optional(),
  encryptedCredentials: zodBuffer,
  createdAt: z.date(),
  updatedAt: z.date(),
  orgId: z.string().uuid(),
  templateId: z.string().uuid(),
  encryptedConnectionDetails: zodBuffer,
  encryptedInternalMetadata: zodBuffer.nullable().optional(),
  gatewayId: z.string().uuid().nullable().optional(),
  gatewayPoolId: z.string().uuid().nullable().optional(),
  recordingConnectionId: z.string().uuid().nullable().optional()
});

export type TPamAccounts = z.infer<typeof PamAccountsSchema>;
export type TPamAccountsInsert = Omit<z.input<typeof PamAccountsSchema>, TImmutableDBKeys>;
export type TPamAccountsUpdate = Partial<Omit<z.input<typeof PamAccountsSchema>, TImmutableDBKeys>>;
