// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PamDiscoverySourceAccountsSchema = z.object({
  id: z.string().uuid(),
  discoverySourceId: z.string().uuid(),
  accountId: z.string().uuid(),
  lastDiscoveredAt: z.date(),
  lastDiscoveredRunId: z.string().uuid().nullable().optional(),
  isStale: z.boolean().default(false).nullable().optional(),
  createdAt: z.date().nullable().optional()
});

export type TPamDiscoverySourceAccounts = z.infer<typeof PamDiscoverySourceAccountsSchema>;
export type TPamDiscoverySourceAccountsInsert = Omit<
  z.input<typeof PamDiscoverySourceAccountsSchema>,
  TImmutableDBKeys
>;
export type TPamDiscoverySourceAccountsUpdate = Partial<
  Omit<z.input<typeof PamDiscoverySourceAccountsSchema>, TImmutableDBKeys>
>;
