// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PamAccountPoliciesSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  name: z.string(),
  description: z.string().nullable().optional(),
  rules: z.unknown(),
  isActive: z.boolean().default(true),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPamAccountPolicies = z.infer<typeof PamAccountPoliciesSchema>;
export type TPamAccountPoliciesInsert = Omit<z.input<typeof PamAccountPoliciesSchema>, TImmutableDBKeys>;
export type TPamAccountPoliciesUpdate = Partial<Omit<z.input<typeof PamAccountPoliciesSchema>, TImmutableDBKeys>>;
