// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PamDiscoverySourcesSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  name: z.string(),
  discoveryType: z.string(),
  gatewayId: z.string().uuid().nullable().optional(),
  gatewayPoolId: z.string().uuid().nullable().optional(),
  credentialAccountId: z.string().uuid(),
  discoveryConfiguration: z.unknown(),
  schedule: z.string().default("manual"),
  lastRunAt: z.date().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPamDiscoverySources = z.infer<typeof PamDiscoverySourcesSchema>;
export type TPamDiscoverySourcesInsert = Omit<z.input<typeof PamDiscoverySourcesSchema>, TImmutableDBKeys>;
export type TPamDiscoverySourcesUpdate = Partial<Omit<z.input<typeof PamDiscoverySourcesSchema>, TImmutableDBKeys>>;
