// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PamDiscoverySourceRunsSchema = z.object({
  id: z.string().uuid(),
  discoverySourceId: z.string().uuid(),
  status: z.string(),
  triggeredBy: z.string(),
  resourcesDiscoveredCount: z.number().default(0).nullable().optional(),
  accountsDiscoveredCount: z.number().default(0).nullable().optional(),
  dependenciesDiscoveredCount: z.number().default(0).nullable().optional(),
  newResourcesCount: z.number().default(0).nullable().optional(),
  staleResourcesCount: z.number().default(0).nullable().optional(),
  newAccountsCount: z.number().default(0).nullable().optional(),
  staleAccountsCount: z.number().default(0).nullable().optional(),
  newDependenciesCount: z.number().default(0).nullable().optional(),
  staleDependenciesCount: z.number().default(0).nullable().optional(),
  progress: z.unknown(),
  errorMessage: z.string().nullable().optional(),
  startedAt: z.date().nullable().optional(),
  completedAt: z.date().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPamDiscoverySourceRuns = z.infer<typeof PamDiscoverySourceRunsSchema>;
export type TPamDiscoverySourceRunsInsert = Omit<z.input<typeof PamDiscoverySourceRunsSchema>, TImmutableDBKeys>;
export type TPamDiscoverySourceRunsUpdate = Partial<
  Omit<z.input<typeof PamDiscoverySourceRunsSchema>, TImmutableDBKeys>
>;
