// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const PamDiscoveredAccountsSchema = z.object({
  id: z.string().uuid(),
  discoverySourceId: z.string().uuid(),
  accountType: z.string(),
  name: z.string(),
  fingerprint: z.string(),
  encryptedDetails: zodBuffer,
  importedAccountId: z.string().uuid().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPamDiscoveredAccounts = z.infer<typeof PamDiscoveredAccountsSchema>;
export type TPamDiscoveredAccountsInsert = Omit<z.input<typeof PamDiscoveredAccountsSchema>, TImmutableDBKeys>;
export type TPamDiscoveredAccountsUpdate = Partial<Omit<z.input<typeof PamDiscoveredAccountsSchema>, TImmutableDBKeys>>;
