// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PartitionedAuditLogsSchema = z.object({
  id: z.string().uuid(),
  actor: z.string(),
  actorMetadata: z.unknown(),
  ipAddress: z.string().nullable().optional(),
  eventType: z.string(),
  eventMetadata: z.unknown().nullable().optional(),
  userAgent: z.string().nullable().optional(),
  userAgentType: z.string().nullable().optional(),
  expiresAt: z.date().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date(),
  orgId: z.string().uuid().nullable().optional(),
  projectId: z.string().nullable().optional(),
  projectName: z.string().nullable().optional()
});

export type TPartitionedAuditLogs = z.infer<typeof PartitionedAuditLogsSchema>;
export type TPartitionedAuditLogsInsert = Omit<z.input<typeof PartitionedAuditLogsSchema>, TImmutableDBKeys>;
export type TPartitionedAuditLogsUpdate = Partial<Omit<z.input<typeof PartitionedAuditLogsSchema>, TImmutableDBKeys>>;
