// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PkiCertificateInstallationsSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  locationType: z.string(),
  locationDetails: z.unknown(),
  locationFingerprint: z.string(),
  name: z.string().nullable().optional(),
  type: z.string().default("unknown"),
  metadata: z.unknown().nullable().optional(),
  lastSeenAt: z.date(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPkiCertificateInstallations = z.infer<typeof PkiCertificateInstallationsSchema>;
export type TPkiCertificateInstallationsInsert = Omit<
  z.input<typeof PkiCertificateInstallationsSchema>,
  TImmutableDBKeys
>;
export type TPkiCertificateInstallationsUpdate = Partial<
  Omit<z.input<typeof PkiCertificateInstallationsSchema>, TImmutableDBKeys>
>;
