// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PkiSubscribersSchema = z.object({
  id: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  projectId: z.string(),
  caId: z.string().uuid().nullable().optional(),
  name: z.string(),
  commonName: z.string(),
  subjectAlternativeNames: z.string().array(),
  ttl: z.string().nullable().optional(),
  keyUsages: z.string().array(),
  extendedKeyUsages: z.string().array(),
  status: z.string(),
  enableAutoRenewal: z.boolean().default(false),
  autoRenewalPeriodInDays: z.number().nullable().optional(),
  lastAutoRenewAt: z.date().nullable().optional(),
  lastOperationStatus: z.string().nullable().optional(),
  lastOperationMessage: z.string().nullable().optional(),
  lastOperationAt: z.date().nullable().optional()
});

export type TPkiSubscribers = z.infer<typeof PkiSubscribersSchema>;
export type TPkiSubscribersInsert = Omit<z.input<typeof PkiSubscribersSchema>, TImmutableDBKeys>;
export type TPkiSubscribersUpdate = Partial<Omit<z.input<typeof PkiSubscribersSchema>, TImmutableDBKeys>>;
