// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PkiDiscoveryInstallationsSchema = z.object({
  id: z.string().guid(),
  discoveryId: z.string().guid(),
  installationId: z.string().guid(),
  lastScannedAt: z.date(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPkiDiscoveryInstallations = z.infer<typeof PkiDiscoveryInstallationsSchema>;
export type TPkiDiscoveryInstallationsInsert = Omit<z.input<typeof PkiDiscoveryInstallationsSchema>, TImmutableDBKeys>;
export type TPkiDiscoveryInstallationsUpdate = Partial<
  Omit<z.input<typeof PkiDiscoveryInstallationsSchema>, TImmutableDBKeys>
>;
