// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "./utils/zod";

import { TImmutableDBKeys } from "./models";

export const PkiEstEnrollmentConfigsSchema = z.object({
  id: z.string().uuid(),
  disableBootstrapCaValidation: z.boolean().default(false).nullable().optional(),
  hashedPassphrase: z.string(),
  encryptedCaChain: zodBuffer.nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPkiEstEnrollmentConfigs = z.infer<typeof PkiEstEnrollmentConfigsSchema>;
export type TPkiEstEnrollmentConfigsInsert = Omit<z.input<typeof PkiEstEnrollmentConfigsSchema>, TImmutableDBKeys>;
export type TPkiEstEnrollmentConfigsUpdate = Partial<
  Omit<z.input<typeof PkiEstEnrollmentConfigsSchema>, TImmutableDBKeys>
>;
