// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PkiAcmeAccountsSchema = z.object({
  id: z.string().uuid(),
  profileId: z.string().uuid(),
  emails: z.string().array(),
  publicKey: z.unknown(),
  publicKeyThumbprint: z.string(),
  alg: z.string(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPkiAcmeAccounts = z.infer<typeof PkiAcmeAccountsSchema>;
export type TPkiAcmeAccountsInsert = Omit<z.input<typeof PkiAcmeAccountsSchema>, TImmutableDBKeys>;
export type TPkiAcmeAccountsUpdate = Partial<Omit<z.input<typeof PkiAcmeAccountsSchema>, TImmutableDBKeys>>;
