// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PkiAcmeOrdersSchema = z.object({
  id: z.string().uuid(),
  accountId: z.string().uuid(),
  certificateId: z.string().uuid().nullable().optional(),
  notBefore: z.date().nullable().optional(),
  notAfter: z.date().nullable().optional(),
  expiresAt: z.date(),
  csr: z.string().nullable().optional(),
  error: z.string().nullable().optional(),
  status: z.string(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPkiAcmeOrders = z.infer<typeof PkiAcmeOrdersSchema>;
export type TPkiAcmeOrdersInsert = Omit<z.input<typeof PkiAcmeOrdersSchema>, TImmutableDBKeys>;
export type TPkiAcmeOrdersUpdate = Partial<Omit<z.input<typeof PkiAcmeOrdersSchema>, TImmutableDBKeys>>;
