// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PkiApplicationProfilesSchema = z.object({
  id: z.string().guid(),
  applicationId: z.string().guid(),
  profileId: z.string().guid(),
  estConfigId: z.string().guid().nullable().optional(),
  apiConfigId: z.string().guid().nullable().optional(),
  acmeConfigId: z.string().guid().nullable().optional(),
  scepConfigId: z.string().guid().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPkiApplicationProfiles = z.infer<typeof PkiApplicationProfilesSchema>;
export type TPkiApplicationProfilesInsert = Omit<z.input<typeof PkiApplicationProfilesSchema>, TImmutableDBKeys>;
export type TPkiApplicationProfilesUpdate = Partial<
  Omit<z.input<typeof PkiApplicationProfilesSchema>, TImmutableDBKeys>
>;
