// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PkiAlertHistorySchema = z.object({
  id: z.string().uuid(),
  alertId: z.string().uuid(),
  triggeredAt: z.date().nullable().optional(),
  hasNotificationSent: z.boolean().default(false).nullable().optional(),
  notificationError: z.string().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPkiAlertHistory = z.infer<typeof PkiAlertHistorySchema>;
export type TPkiAlertHistoryInsert = Omit<z.input<typeof PkiAlertHistorySchema>, TImmutableDBKeys>;
export type TPkiAlertHistoryUpdate = Partial<Omit<z.input<typeof PkiAlertHistorySchema>, TImmutableDBKeys>>;
