// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const PkiApplicationsSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  name: z.string(),
  slug: z.string(),
  description: z.string().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TPkiApplications = z.infer<typeof PkiApplicationsSchema>;
export type TPkiApplicationsInsert = Omit<z.input<typeof PkiApplicationsSchema>, TImmutableDBKeys>;
export type TPkiApplicationsUpdate = Partial<Omit<z.input<typeof PkiApplicationsSchema>, TImmutableDBKeys>>;
