// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ProjectSlackConfigsSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  slackIntegrationId: z.string().uuid(),
  isAccessRequestNotificationEnabled: z.boolean().default(false),
  accessRequestChannels: z.string().default(""),
  isSecretRequestNotificationEnabled: z.boolean().default(false),
  secretRequestChannels: z.string().default(""),
  createdAt: z.date(),
  updatedAt: z.date(),
  isSecretSyncErrorNotificationEnabled: z.boolean().default(false),
  secretSyncErrorChannels: z.string().default("")
});

export type TProjectSlackConfigs = z.infer<typeof ProjectSlackConfigsSchema>;
export type TProjectSlackConfigsInsert = Omit<z.input<typeof ProjectSlackConfigsSchema>, TImmutableDBKeys>;
export type TProjectSlackConfigsUpdate = Partial<Omit<z.input<typeof ProjectSlackConfigsSchema>, TImmutableDBKeys>>;
