// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ProjectTemplateUserMembershipsSchema = z.object({
  id: z.string().uuid(),
  projectTemplateId: z.string().uuid(),
  membershipId: z.string().uuid(),
  roles: z.string().array(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TProjectTemplateUserMemberships = z.infer<typeof ProjectTemplateUserMembershipsSchema>;
export type TProjectTemplateUserMembershipsInsert = Omit<
  z.input<typeof ProjectTemplateUserMembershipsSchema>,
  TImmutableDBKeys
>;
export type TProjectTemplateUserMembershipsUpdate = Partial<
  Omit<z.input<typeof ProjectTemplateUserMembershipsSchema>, TImmutableDBKeys>
>;
