// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ProjectAccessRequestsSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string(),
  requesterUserId: z.string().uuid(),
  status: z.string().default("pending"),
  comment: z.string().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TProjectAccessRequests = z.infer<typeof ProjectAccessRequestsSchema>;
export type TProjectAccessRequestsInsert = Omit<z.input<typeof ProjectAccessRequestsSchema>, TImmutableDBKeys>;
export type TProjectAccessRequestsUpdate = Partial<Omit<z.input<typeof ProjectAccessRequestsSchema>, TImmutableDBKeys>>;
