// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ResourceGcpAuthsSchema = z.object({
  id: z.string().uuid(),
  authMethodId: z.string().uuid(),
  type: z.string().default("gce"),
  allowedServiceAccounts: z.string().default(""),
  allowedProjects: z.string().default(""),
  allowedZones: z.string().default(""),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TResourceGcpAuths = z.infer<typeof ResourceGcpAuthsSchema>;
export type TResourceGcpAuthsInsert = Omit<z.input<typeof ResourceGcpAuthsSchema>, TImmutableDBKeys>;
export type TResourceGcpAuthsUpdate = Partial<Omit<z.input<typeof ResourceGcpAuthsSchema>, TImmutableDBKeys>>;
