// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ResourceAwsAuthsSchema = z.object({
  id: z.string().uuid(),
  authMethodId: z.string().uuid(),
  stsEndpoint: z.string(),
  allowedPrincipalArns: z.string().default(""),
  allowedAccountIds: z.string().default(""),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TResourceAwsAuths = z.infer<typeof ResourceAwsAuthsSchema>;
export type TResourceAwsAuthsInsert = Omit<z.input<typeof ResourceAwsAuthsSchema>, TImmutableDBKeys>;
export type TResourceAwsAuthsUpdate = Partial<Omit<z.input<typeof ResourceAwsAuthsSchema>, TImmutableDBKeys>>;
