// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ResourceTokenAuthsSchema = z.object({
  id: z.string().uuid(),
  orgId: z.string().uuid(),
  tokenHash: z.string(),
  ttl: z.number().default(3600),
  expiresAt: z.date(),
  createdAt: z.date(),
  updatedAt: z.date(),
  authMethodId: z.string().uuid()
});

export type TResourceTokenAuths = z.infer<typeof ResourceTokenAuthsSchema>;
export type TResourceTokenAuthsInsert = Omit<z.input<typeof ResourceTokenAuthsSchema>, TImmutableDBKeys>;
export type TResourceTokenAuthsUpdate = Partial<Omit<z.input<typeof ResourceTokenAuthsSchema>, TImmutableDBKeys>>;
