// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const ResourceAuthMethodsSchema = z.object({
  id: z.string().guid(),
  gatewayId: z.string().guid().nullable().optional(),
  method: z.string(),
  createdAt: z.date(),
  updatedAt: z.date(),
  relayId: z.string().guid().nullable().optional(),
  kmipServerId: z.string().guid().nullable().optional(),
  agentVaultProxyId: z.string().guid().nullable().optional()
});

export type TResourceAuthMethods = z.infer<typeof ResourceAuthMethodsSchema>;
export type TResourceAuthMethodsInsert = Omit<z.input<typeof ResourceAuthMethodsSchema>, TImmutableDBKeys>;
export type TResourceAuthMethodsUpdate = Partial<Omit<z.input<typeof ResourceAuthMethodsSchema>, TImmutableDBKeys>>;
