// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SamlGroupMappingsSchema = z.object({
  id: z.string().uuid(),
  samlConfigId: z.string().uuid(),
  samlGroupName: z.string(),
  groupId: z.string().uuid().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSamlGroupMappings = z.infer<typeof SamlGroupMappingsSchema>;
export type TSamlGroupMappingsInsert = Omit<z.input<typeof SamlGroupMappingsSchema>, TImmutableDBKeys>;
export type TSamlGroupMappingsUpdate = Partial<Omit<z.input<typeof SamlGroupMappingsSchema>, TImmutableDBKeys>>;