// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretApprovalPoliciesGroupApproversSchema = z.object({
  id: z.string().uuid(),
  approverGroupId: z.string().uuid(),
  policyId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecretApprovalPoliciesGroupApprovers = z.infer<typeof SecretApprovalPoliciesGroupApproversSchema>;
export type TSecretApprovalPoliciesGroupApproversInsert = Omit<
  z.input<typeof SecretApprovalPoliciesGroupApproversSchema>,
  TImmutableDBKeys
>;
export type TSecretApprovalPoliciesGroupApproversUpdate = Partial<
  Omit<z.input<typeof SecretApprovalPoliciesGroupApproversSchema>, TImmutableDBKeys>
>;
