// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretApprovalRequestSecretTagsV2Schema = z.object({
  id: z.string().guid(),
  secretId: z.string().guid(),
  tagId: z.string().guid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecretApprovalRequestSecretTagsV2 = z.infer<typeof SecretApprovalRequestSecretTagsV2Schema>;
export type TSecretApprovalRequestSecretTagsV2Insert = Omit<
  z.input<typeof SecretApprovalRequestSecretTagsV2Schema>,
  TImmutableDBKeys
>;
export type TSecretApprovalRequestSecretTagsV2Update = Partial<
  Omit<z.input<typeof SecretApprovalRequestSecretTagsV2Schema>, TImmutableDBKeys>
>;
