// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretChangeRequestsSchema = z.object({
  id: z.string().uuid(),
  approvalRequestId: z.string().uuid(),
  folderId: z.string().uuid(),
  statusChangedByUserId: z.string().uuid().nullable().optional(),
  slug: z.string(),
  hasMerged: z.boolean().default(false),
  conflicts: z.unknown().nullable().optional(),
  commitMessage: z.string().nullable().optional(),
  bypassReason: z.string().nullable().optional(),
  isReplicated: z.boolean().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecretChangeRequests = z.infer<typeof SecretChangeRequestsSchema>;
export type TSecretChangeRequestsInsert = Omit<z.input<typeof SecretChangeRequestsSchema>, TImmutableDBKeys>;
export type TSecretChangeRequestsUpdate = Partial<Omit<z.input<typeof SecretChangeRequestsSchema>, TImmutableDBKeys>>;
