// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretApprovalPoliciesBypassersSchema = z.object({
  id: z.string().guid(),
  bypasserGroupId: z.string().guid().nullable().optional(),
  bypasserUserId: z.string().guid().nullable().optional(),
  policyId: z.string().guid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecretApprovalPoliciesBypassers = z.infer<typeof SecretApprovalPoliciesBypassersSchema>;
export type TSecretApprovalPoliciesBypassersInsert = Omit<
  z.input<typeof SecretApprovalPoliciesBypassersSchema>,
  TImmutableDBKeys
>;
export type TSecretApprovalPoliciesBypassersUpdate = Partial<
  Omit<z.input<typeof SecretApprovalPoliciesBypassersSchema>, TImmutableDBKeys>
>;
