// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const SecretScanningFindingsSchema = z.object({
  id: z.string().uuid(),
  dataSourceName: z.string(),
  dataSourceType: z.string(),
  resourceName: z.string(),
  resourceType: z.string(),
  rule: z.string(),
  severity: z.string(),
  status: z.string().default("unresolved"),
  remarks: z.string().nullable().optional(),
  fingerprint: z.string(),
  projectId: z.string(),
  scanId: z.string().uuid().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date(),
  encryptedDetails: zodBuffer
});

export type TSecretScanningFindings = z.infer<typeof SecretScanningFindingsSchema>;
export type TSecretScanningFindingsInsert = Omit<z.input<typeof SecretScanningFindingsSchema>, TImmutableDBKeys>;
export type TSecretScanningFindingsUpdate = Partial<
  Omit<z.input<typeof SecretScanningFindingsSchema>, TImmutableDBKeys>
>;
