// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const SecretShareBrandingAssetsSchema = z.object({
  id: z.string().uuid(),
  orgId: z.string().uuid(),
  assetType: z.string(),
  data: zodBuffer,
  contentType: z.string(),
  size: z.number(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecretShareBrandingAssets = z.infer<typeof SecretShareBrandingAssetsSchema>;
export type TSecretShareBrandingAssetsInsert = Omit<z.input<typeof SecretShareBrandingAssetsSchema>, TImmutableDBKeys>;
export type TSecretShareBrandingAssetsUpdate = Partial<
  Omit<z.input<typeof SecretShareBrandingAssetsSchema>, TImmutableDBKeys>
>;
