// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretHttpProxyConfigsSchema = z.object({
  id: z.string().uuid(),
  secretId: z.string().uuid(),
  placeholder: z.string(),
  rules: z.unknown(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecretHttpProxyConfigs = z.infer<typeof SecretHttpProxyConfigsSchema>;
export type TSecretHttpProxyConfigsInsert = Omit<z.input<typeof SecretHttpProxyConfigsSchema>, TImmutableDBKeys>;
export type TSecretHttpProxyConfigsUpdate = Partial<Omit<z.input<typeof SecretHttpProxyConfigsSchema>, TImmutableDBKeys>>;
