// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretRotationOutputV2Schema = z.object({
  id: z.string().uuid(),
  key: z.string(),
  secretId: z.string().uuid(),
  rotationId: z.string().uuid()
});

export type TSecretRotationOutputV2 = z.infer<typeof SecretRotationOutputV2Schema>;
export type TSecretRotationOutputV2Insert = Omit<z.input<typeof SecretRotationOutputV2Schema>, TImmutableDBKeys>;
export type TSecretRotationOutputV2Update = Partial<
  Omit<z.input<typeof SecretRotationOutputV2Schema>, TImmutableDBKeys>
>;
