// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const SecretApprovalRequestsSecretsV2Schema = z.object({
  id: z.string().guid(),
  version: z.number().nullable().optional(),
  key: z.string(),
  encryptedValue: zodBuffer.nullable().optional(),
  encryptedComment: zodBuffer.nullable().optional(),
  reminderNote: z.string().nullable().optional(),
  reminderRepeatDays: z.number().nullable().optional(),
  skipMultilineEncoding: z.boolean().nullable().optional(),
  metadata: z.unknown().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date(),
  requestId: z.string().guid(),
  op: z.string(),
  secretId: z.string().guid().nullable().optional(),
  secretVersion: z.string().guid().nullable().optional(),
  secretMetadata: z.unknown().nullable().optional(),
  internalMetadata: z.unknown().nullable().optional()
});

export type TSecretApprovalRequestsSecretsV2 = z.infer<typeof SecretApprovalRequestsSecretsV2Schema>;
export type TSecretApprovalRequestsSecretsV2Insert = Omit<
  z.input<typeof SecretApprovalRequestsSecretsV2Schema>,
  TImmutableDBKeys
>;
export type TSecretApprovalRequestsSecretsV2Update = Partial<
  Omit<z.input<typeof SecretApprovalRequestsSecretsV2Schema>, TImmutableDBKeys>
>;
