// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SignupOnboardingResponsesSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  orgId: z.string().uuid(),
  selectedProducts: z.string().array().nullable().optional(),
  isExploring: z.boolean().nullable().optional(),
  launchDestination: z.string().nullable().optional(),
  attributionSource: z.string().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSignupOnboardingResponses = z.infer<typeof SignupOnboardingResponsesSchema>;
export type TSignupOnboardingResponsesInsert = Omit<z.input<typeof SignupOnboardingResponsesSchema>, TImmutableDBKeys>;
export type TSignupOnboardingResponsesUpdate = Partial<
  Omit<z.input<typeof SignupOnboardingResponsesSchema>, TImmutableDBKeys>
>;
