// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const UserFeatureDiscoveriesSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  releaseId: z.string(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TUserFeatureDiscoveries = z.infer<typeof UserFeatureDiscoveriesSchema>;
export type TUserFeatureDiscoveriesInsert = Omit<z.input<typeof UserFeatureDiscoveriesSchema>, TImmutableDBKeys>;
export type TUserFeatureDiscoveriesUpdate = Partial<
  Omit<z.input<typeof UserFeatureDiscoveriesSchema>, TImmutableDBKeys>
>;
