// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const UserSecretsSecureNoteSchema = z.object({
  id: z.string().uuid(),
  iv: z.string().nullable().optional(),
  tag: z.string().nullable().optional(),
  secretId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  content: zodBuffer.nullable().optional(),
  title: zodBuffer.nullable().optional()
});

export type TUserSecretsSecureNote = z.infer<typeof UserSecretsSecureNoteSchema>;
export type TUserSecretsSecureNoteInsert = Omit<z.input<typeof UserSecretsSecureNoteSchema>, TImmutableDBKeys>;
export type TUserSecretsSecureNoteUpdate = Partial<Omit<z.input<typeof UserSecretsSecureNoteSchema>, TImmutableDBKeys>>;
