// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const UserSecretsSchema = z.object({
  id: z.string().uuid(),
  encryptedTitle: z.string().nullable().optional(),
  encryptedContent: z.string().nullable().optional(),
  encryptedUsername: z.string().nullable().optional(),
  encryptedPassword: z.string().nullable().optional(),
  encryptedCardNumber: z.string().nullable().optional(),
  encryptedExpiryDate: z.string().nullable().optional(),
  encryptedCVV: z.string().nullable().optional(),
  userId: z.string().uuid(),
  orgId: z.string().uuid()
});

export type TUserSecrets = z.infer<typeof UserSecretsSchema>;
export type TUserSecretsInsert = Omit<z.input<typeof UserSecretsSchema>, TImmutableDBKeys>;
export type TUserSecretsUpdate = Partial<Omit<z.input<typeof UserSecretsSchema>, TImmutableDBKeys>>;
