// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const UserPoliciesSchema = z.object({
  id: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  projectId: z.string(),
  name: z.string(),
  target: z.string()
});

export type TUserPolicies = z.infer<typeof UserPoliciesSchema>;
export type TUserPoliciesInsert = Omit<z.input<typeof UserPoliciesSchema>, TImmutableDBKeys>;
export type TUserPoliciesUpdate = Partial<Omit<z.input<typeof UserPoliciesSchema>, TImmutableDBKeys>>;
