// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const UserSecretActivationSchema = z.object({
  id: z.string().uuid(),
  firstSecretCreatedAt: z.date().nullable().optional(),
  returnedAfterThreeDaysAt: z.date().nullable().optional(),
  returnedAfterSevenDaysAt: z.date().nullable().optional(),
  userId: z.string().uuid(),
  orgId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TUserSecretActivation = z.infer<typeof UserSecretActivationSchema>;
export type TUserSecretActivationInsert = Omit<z.input<typeof UserSecretActivationSchema>, TImmutableDBKeys>;
export type TUserSecretActivationUpdate = Partial<Omit<z.input<typeof UserSecretActivationSchema>, TImmutableDBKeys>>;
