// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const UserSecretSchema = z.object({
  id: z.string().uuid(),
  name: z.string().nullable().optional(),
  encryptedValue: z.string(),
  iv: z.string(),
  hashedHex: z.string(),
  tag: z.string(),
  userId: z.string().uuid(),
  orgId: z.string().uuid(),
  secretType: z.string().default("login"),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TUserSecret = z.infer<typeof UserSecretSchema>;
export type TUserSecretInsert = Omit<z.input<typeof UserSecretSchema>, TImmutableDBKeys>;
export type TUserSecretUpdate = Partial<Omit<z.input<typeof UserSecretSchema>, TImmutableDBKeys>>;
