// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const VaultExternalMigrationConfigsSchema = z.object({
  id: z.string().uuid(),
  orgId: z.string().uuid(),
  namespace: z.string(),
  connectionId: z.string().uuid().nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TVaultExternalMigrationConfigs = z.infer<typeof VaultExternalMigrationConfigsSchema>;
export type TVaultExternalMigrationConfigsInsert = Omit<
  z.input<typeof VaultExternalMigrationConfigsSchema>,
  TImmutableDBKeys
>;
export type TVaultExternalMigrationConfigsUpdate = Partial<
  Omit<z.input<typeof VaultExternalMigrationConfigsSchema>, TImmutableDBKeys>
>;
