name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which Infisical product is this bug related to?
      options:
        - Platform/Access controls/Other
        - Secret Manager
        - Certificate Manager (PKI)
        - KMS
        - Secret Scanning
        - Privileged Access Manager (PAM)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: dropdown
    id: deployment-type
    attributes:
      label: Deployment Type
      description: What deployment type are you experiencing the issue on?
      options:
        - Infisical Cloud
        - Self-hosted
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here (e.g., version numbers, browser, OS).
    validations:
      required: false
