name: Report a documentation bug
about: Report an issue with the Infisical documentation.
title: 'Docs: '
labels: documentation
assignees: ''
body:
  - type: textarea
    attributes:
      label: What is the documentation issue?
      description: 'Example: There is a typo in this sentence.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Provide any further information or screenshots that could help us resolve the issue.
    validations:
      required: true
  - type: textarea 
    attributes:
      label: Links to the relevant documentation pages.
      description: 'Example: https://infisical.com/docs/documentation/getting-started/overview'
    validations:
      required: false
