# permissions for end users to edit infisicalpushsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8-operator
    app.kubernetes.io/managed-by: kustomize
  name: infisicalpushsecret-editor-role
rules:
  - apiGroups:
      - secrets.infisical.com
    resources:
      - infisicalpushsecrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - secrets.infisical.com
    resources:
      - infisicalpushsecrets/status
    verbs:
      - get
