# permissions for end users to edit infisicalsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: infisicalsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8-operator
    app.kubernetes.io/part-of: k8-operator
    app.kubernetes.io/managed-by: kustomize
  name: infisicalsecret-editor-role
rules:
- apiGroups:
  - secrets.infisical.com
  resources:
  - infisicalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.infisical.com
  resources:
  - infisicalsecrets/status
  verbs:
  - get
