export const getDefaultOnPremFeatures = () => {
  return {
    _id: null,
    slug: null,
    tier: -1,
    workspaceLimit: null,
    workspacesUsed: 0,
    dynamicSecret: false,
    memberLimit: null,
    identityLimit: null,
    subOrganization: false,
    environmentLimit: null,
    environmentsUsed: 0,
    secretVersioning: true,
    pitRecovery: false,
    ipAllowlisting: true,
    rbac: false,
    customRateLimits: false,
    customAlerts: false,
    auditLogs: false,
    auditLogsRetentionDays: 0,
    auditLogStreams: false,
    auditLogStreamLimit: 3,
    githubOrgSync: false,
    samlSSO: true,
    enforceGoogleSSO: false,
    hsm: false,
    oidcSSO: true,
    secretAccessInsights: false,
    scim: true,
    ldap: true,
    groups: false,
    status: null,
    trial_end: null,
    has_used_trial: true,
    secretApproval: true,
    secretRotation: true,
    instanceUserManagement: false,
    externalKms: false,
    rateLimits: {
      readLimit: 60,
      writeLimit: 200,
      secretsLimit: 40
    },
    kmsPqc: false,
    enforceMfa: false,
    projectTemplates: false,
    kmip: false,
    gateway: false,
    gatewayPool: false,
    pamSlackNotifications: false,
    secretScanning: false,
    enterpriseSecretSyncs: false,
    enterpriseAppConnections: true,
    machineIdentityAuthTemplates: false,
    fips: true,
    eventSubscriptions: false,
    secretShareExternalBranding: false,
    honeyTokens: false,
    honeyTokenLimit: 0,
    secretsBrokering: true,
    secretSyncLimit: null,
    maxPamAccounts: null,
    // PKI / Cert Manager
    pkiAcme: true,
    pkiEst: false,
    pkiScep: false,
    pkiPqc: false,
    caCrl: true,
    pkiWildcardSans: true,
    pkiEnterpriseCaIntegrations: false,
    pkiExternalIntermediateCa: false,
    pkiDiscovery: false,
    pkiEnterpriseAlerting: false,
    pkiApprovals: false,
    pkiSyncs: false,
    pkiLegacyTemplates: false,
    pkiCodeSigning: false,
    maxInternalCas: null,
    maxSansPerCertificate: null,
    // product gating
    pam: null,
    certManager: null,
    secretsTemporaryAccess: null,
    enterprisePamAccount: null,
    crossProjectSecretSharing: false,
    secretsFolderRbac: true
  };
};

export const getLicenseKeyConfig = () => {
  return {
    isValid: false
  };
};
