export enum AppConnection {
  AWS = "aws",
  GitHub = "github",
  GCP = "gcp",
  AzureKeyVault = "azure-key-vault",
  AzureAppConfiguration = "azure-app-configuration",
  AzureClientSecrets = "azure-client-secrets",
  Databricks = "databricks",
  Humanitec = "humanitec",
  TerraformCloud = "terraform-cloud",
  Vercel = "vercel",
  Postgres = "postgres",
  MsSql = "mssql",
  Camunda = "camunda",
  Windmill = "windmill",
  Auth0 = "auth0",
  HCVault = "hashicorp-vault",
  LDAP = "ldap",
  TeamCity = "teamcity",
  OCI = "oci"
}
