import { AppConnection } from "@app/services/app-connection/app-connection-enums";
import { SecretSync, SecretSyncPlanType } from "@app/services/secret-sync/secret-sync-enums";

export const SECRET_SYNC_NAME_MAP: Record<SecretSync, string> = {
  [SecretSync.AWSParameterStore]: "AWS Parameter Store",
  [SecretSync.AWSSecretsManager]: "AWS Secrets Manager",
  [SecretSync.GitHub]: "GitHub",
  [SecretSync.GCPSecretManager]: "GCP Secret Manager",
  [SecretSync.AzureKeyVault]: "Azure Key Vault",
  [SecretSync.AzureAppConfiguration]: "Azure App Configuration",
  [SecretSync.AzureDevOps]: "Azure DevOps",
  [SecretSync.Databricks]: "Databricks",
  [SecretSync.Humanitec]: "Humanitec",
  [SecretSync.TerraformCloud]: "Terraform Cloud",
  [SecretSync.Camunda]: "Camunda",
  [SecretSync.Vercel]: "Vercel",
  [SecretSync.Windmill]: "Windmill",
  [SecretSync.HCVault]: "Hashicorp Vault",
  [SecretSync.TeamCity]: "TeamCity",
  [SecretSync.OCIVault]: "OCI Vault",
  [SecretSync.OnePass]: "1Password",
  [SecretSync.Heroku]: "Heroku",
  [SecretSync.Render]: "Render",
  [SecretSync.Flyio]: "Fly.io",
  [SecretSync.GitLab]: "GitLab",
  [SecretSync.CloudflarePages]: "Cloudflare Pages",
  [SecretSync.CloudflareWorkers]: "Cloudflare Workers",
  [SecretSync.Supabase]: "Supabase",
  [SecretSync.Zabbix]: "Zabbix",
  [SecretSync.Railway]: "Railway",
  [SecretSync.Checkly]: "Checkly",
  [SecretSync.DigitalOceanAppPlatform]: "Digital Ocean App Platform",
  [SecretSync.Bitbucket]: "Bitbucket"
};

export const SECRET_SYNC_CONNECTION_MAP: Record<SecretSync, AppConnection> = {
  [SecretSync.AWSParameterStore]: AppConnection.AWS,
  [SecretSync.AWSSecretsManager]: AppConnection.AWS,
  [SecretSync.GitHub]: AppConnection.GitHub,
  [SecretSync.GCPSecretManager]: AppConnection.GCP,
  [SecretSync.AzureKeyVault]: AppConnection.AzureKeyVault,
  [SecretSync.AzureAppConfiguration]: AppConnection.AzureAppConfiguration,
  [SecretSync.AzureDevOps]: AppConnection.AzureDevOps,
  [SecretSync.Databricks]: AppConnection.Databricks,
  [SecretSync.Humanitec]: AppConnection.Humanitec,
  [SecretSync.TerraformCloud]: AppConnection.TerraformCloud,
  [SecretSync.Camunda]: AppConnection.Camunda,
  [SecretSync.Vercel]: AppConnection.Vercel,
  [SecretSync.Windmill]: AppConnection.Windmill,
  [SecretSync.HCVault]: AppConnection.HCVault,
  [SecretSync.TeamCity]: AppConnection.TeamCity,
  [SecretSync.OCIVault]: AppConnection.OCI,
  [SecretSync.OnePass]: AppConnection.OnePass,
  [SecretSync.Heroku]: AppConnection.Heroku,
  [SecretSync.Render]: AppConnection.Render,
  [SecretSync.Flyio]: AppConnection.Flyio,
  [SecretSync.GitLab]: AppConnection.GitLab,
  [SecretSync.CloudflarePages]: AppConnection.Cloudflare,
  [SecretSync.CloudflareWorkers]: AppConnection.Cloudflare,
  [SecretSync.Supabase]: AppConnection.Supabase,
  [SecretSync.Zabbix]: AppConnection.Zabbix,
  [SecretSync.Railway]: AppConnection.Railway,
  [SecretSync.Checkly]: AppConnection.Checkly,
  [SecretSync.DigitalOceanAppPlatform]: AppConnection.DigitalOcean,
  [SecretSync.Bitbucket]: AppConnection.Bitbucket
};

export const SECRET_SYNC_PLAN_MAP: Record<SecretSync, SecretSyncPlanType> = {
  [SecretSync.AWSParameterStore]: SecretSyncPlanType.Regular,
  [SecretSync.AWSSecretsManager]: SecretSyncPlanType.Regular,
  [SecretSync.GitHub]: SecretSyncPlanType.Regular,
  [SecretSync.GCPSecretManager]: SecretSyncPlanType.Regular,
  [SecretSync.AzureKeyVault]: SecretSyncPlanType.Regular,
  [SecretSync.AzureAppConfiguration]: SecretSyncPlanType.Regular,
  [SecretSync.AzureDevOps]: SecretSyncPlanType.Regular,
  [SecretSync.Databricks]: SecretSyncPlanType.Regular,
  [SecretSync.Humanitec]: SecretSyncPlanType.Regular,
  [SecretSync.TerraformCloud]: SecretSyncPlanType.Regular,
  [SecretSync.Camunda]: SecretSyncPlanType.Regular,
  [SecretSync.Vercel]: SecretSyncPlanType.Regular,
  [SecretSync.Windmill]: SecretSyncPlanType.Regular,
  [SecretSync.HCVault]: SecretSyncPlanType.Regular,
  [SecretSync.TeamCity]: SecretSyncPlanType.Regular,
  [SecretSync.OCIVault]: SecretSyncPlanType.Enterprise,
  [SecretSync.OnePass]: SecretSyncPlanType.Regular,
  [SecretSync.Heroku]: SecretSyncPlanType.Regular,
  [SecretSync.Render]: SecretSyncPlanType.Regular,
  [SecretSync.Flyio]: SecretSyncPlanType.Regular,
  [SecretSync.GitLab]: SecretSyncPlanType.Regular,
  [SecretSync.CloudflarePages]: SecretSyncPlanType.Regular,
  [SecretSync.CloudflareWorkers]: SecretSyncPlanType.Regular,
  [SecretSync.Supabase]: SecretSyncPlanType.Regular,
  [SecretSync.Zabbix]: SecretSyncPlanType.Regular,
  [SecretSync.Railway]: SecretSyncPlanType.Regular,
  [SecretSync.Checkly]: SecretSyncPlanType.Regular,
  [SecretSync.DigitalOceanAppPlatform]: SecretSyncPlanType.Regular,
  [SecretSync.Bitbucket]: SecretSyncPlanType.Regular
};
