import { SecretRotation } from "@app/ee/services/secret-rotation-v2/secret-rotation-v2-enums";
import { TSecretRotationV2ListItem } from "@app/ee/services/secret-rotation-v2/secret-rotation-v2-types";
import { AppConnection } from "@app/services/app-connection/app-connection-enums";

/**
 * Every permission the Managed API Keys API accepts. There is no wildcard, no unrestricted key type
 * and no endpoint that lists these, so full access means naming all 158. Verified by probing each
 * one against a gated sandbox.
 */
export const STRIPE_API_KEY_PERMISSIONS = [
  "account_link_write",
  "adjustment_read",
  "api_key_write",
  "apple_pay_domain_read",
  "apple_pay_domain_write",
  "application_fee_read",
  "application_fee_write",
  "balance_read",
  "balance_transaction_source_read",
  "billing_analytics_meter_usage_read",
  "billing_clock_read",
  "billing_clock_write",
  "billing_intent_read",
  "billing_meter_event_read",
  "billing_meter_event_write",
  "billing_meter_read",
  "billing_meter_write",
  "billing_profile_read",
  "billing_profile_write",
  "billing_settings_read",
  "billing_settings_write",
  "capital_for_platforms_financing_offer_read",
  "capital_for_platforms_financing_offer_write",
  "capital_for_platforms_financing_summary_read",
  "capital_for_platforms_financing_transaction_read",
  "charge_read",
  "charge_write",
  "checkout_session_read",
  "checkout_session_write",
  "confirmation_token_client_read",
  "confirmation_token_client_write",
  "confirmation_token_read",
  "connected_account_read",
  "coupon_read",
  "coupon_write",
  "credit_note_read",
  "credit_note_write",
  "customer_portal_read",
  "customer_portal_write",
  "customer_read",
  "customer_session_read",
  "customer_session_write",
  "customer_write",
  "dispute_read",
  "dispute_write",
  "edit_link_write",
  "entitlement_read",
  "event_read",
  "fee_domain_resources_read",
  "file_read",
  "file_write",
  "financial_account_read",
  "inbound_transfer_read",
  "invoice_read",
  "invoice_write",
  "issuing_authorization_read",
  "issuing_authorization_write",
  "issuing_card_read",
  "issuing_card_write",
  "issuing_cardholder_read",
  "issuing_cardholder_write",
  "issuing_credit_ledger_read",
  "issuing_credit_ledger_write",
  "issuing_dispute_read",
  "issuing_dispute_write",
  "issuing_read",
  "issuing_token_network_data_read",
  "issuing_token_read",
  "issuing_token_write",
  "issuing_transaction_read",
  "issuing_transaction_write",
  "issuing_verification_write",
  "issuing_write",
  "mandate_read",
  "mandate_write",
  "order_read",
  "order_write",
  "outbound_payment_read",
  "outbound_transfer_read",
  "payment_intent_read",
  "payment_intent_write",
  "payment_links_read",
  "payment_links_write",
  "payment_method_configurations_read",
  "payment_method_configurations_write",
  "payment_method_domain_read",
  "payment_method_domain_write",
  "payment_method_read",
  "payment_method_write",
  "payment_records_read",
  "payment_records_write",
  "payout_intent_read",
  "payout_read",
  "payout_write",
  "plan_read",
  "plan_write",
  "product_catalog_import_read",
  "product_catalog_import_write",
  "product_read",
  "product_write",
  "promotion_code_read",
  "promotion_code_write",
  "provisioning_account_request_read",
  "provisioning_account_request_write",
  "provisioning_project_read",
  "provisioning_project_write",
  "provisioning_resource_read",
  "provisioning_resource_write",
  "quote_read",
  "quote_write",
  "rate_card_subscription_write",
  "rate_card_write",
  "received_credit_read",
  "received_debit_read",
  "recipient_verification_read",
  "report_runs_and_report_types_read",
  "report_runs_and_report_types_write",
  "review_read",
  "review_write",
  "secret_read",
  "secret_write",
  "setup_intent_read",
  "setup_intent_write",
  "shipping_rate_read",
  "shipping_rate_write",
  "sku_read",
  "sku_write",
  "source_read",
  "source_write",
  "subscription_read",
  "subscription_write",
  "tax_calculations_and_transactions_read",
  "tax_calculations_and_transactions_write",
  "tax_locations_read",
  "tax_locations_write",
  "tax_rate_read",
  "tax_rate_write",
  "tax_settings_read",
  "tax_settings_write",
  "terminal_configuration_read",
  "terminal_configuration_write",
  "terminal_connection_token_write",
  "terminal_location_read",
  "terminal_location_write",
  "terminal_reader_read",
  "terminal_reader_write",
  "token_read",
  "token_write",
  "top_up_read",
  "top_up_write",
  "transaction_read",
  "transfer_read",
  "transfer_write",
  "treasury_transaction_read",
  "usage_record_read",
  "usage_record_write",
  "webhook_read",
  "webhook_write"
] as const;

export const STRIPE_API_KEY_ROTATION_LIST_OPTION: TSecretRotationV2ListItem = {
  name: "Stripe API Key",
  type: SecretRotation.StripeApiKey,
  connection: AppConnection.Stripe,
  template: {
    secretsMapping: {
      apiKey: "STRIPE_API_KEY"
    },
    permissions: [...STRIPE_API_KEY_PERMISSIONS]
  }
};
