export {
  useAddIdentityToWorkspace,
  useAddUserToWorkspace,
  useCreateWorkspace,
  useCreateWsEnvironment,
  useDeleteIdentityFromWorkspace,
  useDeleteUserFromWorkspace,
  useDeleteWorkspace,
  useDeleteWsEnvironment,
  useGetUserWorkspaceMemberships,
  useGetUserWorkspaces,
  useGetWorkspaceAuthorizations,
  useGetWorkspaceById,
  useGetWorkspaceIdentityMemberships,
  useGetWorkspaceIndexStatus,
  useGetWorkspaceIntegrations,
  useGetWorkspaceSecrets,
  useGetWorkspaceUsers,
  useNameWorkspaceSecrets,
  useRenameWorkspace,
  useToggleAutoCapitalization,
  useUpdateIdentityWorkspaceRole,
  useUpdateUserWorkspaceRole,
  useUpdateWsEnvironment
} from "./queries";
