root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/infisical"
  cmd = "go build -o ./tmp/infisical ./cmd/infisical/..."
  delay = 1000
  exclude_dir = ["tmp", "vendor", "node_modules"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "toml"]
  kill_delay = "0s"
  send_interrupt = true
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
