export const ALARM_CHANNEL_RETRY_CONFIG = { maxRetries: 3, delayMs: 3000 };

export const RETRYABLE_NETWORK_ERRORS = [
  "ECONNREFUSED",
  "ENOTFOUND",
  "ETIMEDOUT",
  "ECONNRESET",
  "ECONNABORTED",
  "ENETUNREACH",
  "EHOSTUNREACH"
];
