# This rule is not used by the project k8-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to secrets.infisical.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8-operator
    app.kubernetes.io/managed-by: kustomize
  name: infisicalsecret-viewer-role
rules:
- apiGroups:
  - secrets.infisical.com
  resources:
  - infisicalsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.infisical.com
  resources:
  - infisicalsecrets/status
  verbs:
  - get
