# permissions for end users to view infisicaldynamicsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8-operator
    app.kubernetes.io/managed-by: kustomize
  name: infisicaldynamicsecret-viewer-role
rules:
- apiGroups:
  - secrets.infisical.com
  resources:
  - infisicaldynamicsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.infisical.com
  resources:
  - infisicaldynamicsecrets/status
  verbs:
  - get
