# permissions for end users to view infisicalpushsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: infisical-operator
    app.kubernetes.io/managed-by: kustomize
  name: infisicalpushsecret-viewer-role
rules:
  - apiGroups:
      - secrets.infisical.com
    resources:
      - infisicalpushsecrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - secrets.infisical.com
    resources:
      - infisicalpushsecrets/status
    verbs:
      - get
