export const MAX_PREVENT_DUPLICATE_SECRET_VALUE_VERSIONS = 25;

export const MAX_SECRET_CONSTRAINT_LENGTH = 65536;

export const MAX_GENERATED_CONSTRAINT_LENGTH = 2048;

export const MAX_CONSTRAINT_PATTERN_LENGTH = 4096;
export const MAX_CONSTRAINT_AFFIX_LENGTH = 1024;
