import { ProjectType } from "../projects/types";
import { EventType, UserAgentType } from "./enums";

export const secretEvents: EventType[] = [
  EventType.GET_SECRETS,
  EventType.GET_SECRET,
  EventType.DELETE_SECRETS,
  EventType.CREATE_SECRETS,
  EventType.UPDATE_SECRETS,
  EventType.CREATE_SECRET,
  EventType.UPDATE_SECRET,
  EventType.DELETE_SECRET
];

export const eventToNameMap: { [K in EventType]: string } = {
  [EventType.GET_SECRETS]: "List secrets",
  [EventType.GET_SECRET]: "Read secret",
  [EventType.DELETE_SECRETS]: "Delete secrets",
  [EventType.CREATE_SECRETS]: "Create secrets",
  [EventType.UPDATE_SECRETS]: "Update secrets",
  [EventType.CREATE_SECRET]: "Create secret",
  [EventType.UPDATE_SECRET]: "Update secret",
  [EventType.DELETE_SECRET]: "Delete secret",
  [EventType.GET_PROJECT_KEY]: "Read project key",
  [EventType.AUTHORIZE_INTEGRATION]: "Authorize integration",
  [EventType.UPDATE_INTEGRATION_AUTH]: "Update integration auth",
  [EventType.UNAUTHORIZE_INTEGRATION]: "Unauthorize integration",
  [EventType.CREATE_INTEGRATION]: "Create integration",
  [EventType.DELETE_INTEGRATION]: "Delete integration",
  [EventType.ADD_TRUSTED_IP]: "Add trusted IP",
  [EventType.UPDATE_TRUSTED_IP]: "Update trusted IP",
  [EventType.DELETE_TRUSTED_IP]: "Delete trusted IP",
  [EventType.CREATE_SERVICE_TOKEN]: "Create service token",
  [EventType.DELETE_SERVICE_TOKEN]: "Delete service token",
  [EventType.CREATE_IDENTITY]: "Create identity",
  [EventType.UPDATE_IDENTITY]: "Update identity",
  [EventType.DELETE_IDENTITY]: "Delete identity",
  [EventType.LOGIN_IDENTITY_UNIVERSAL_AUTH]: "Login via universal auth",
  [EventType.ADD_IDENTITY_UNIVERSAL_AUTH]: "Add universal auth",
  [EventType.UPDATE_IDENTITY_UNIVERSAL_AUTH]: "Update universal auth",
  [EventType.GET_IDENTITY_UNIVERSAL_AUTH]: "Get universal auth",
  [EventType.CREATE_IDENTITY_UNIVERSAL_AUTH_CLIENT_SECRET]: "Create universal auth client secret",
  [EventType.REVOKE_IDENTITY_UNIVERSAL_AUTH_CLIENT_SECRET]: "Revoke universal auth client secret",
  [EventType.CLEAR_IDENTITY_UNIVERSAL_AUTH_LOCKOUTS]: "Clear universal auth lockouts",
  [EventType.GET_IDENTITY_UNIVERSAL_AUTH_CLIENT_SECRETS]: "Get universal auth client secrets",
  [EventType.GET_IDENTITY_UNIVERSAL_AUTH_CLIENT_SECRET_BY_ID]:
    "Get universal auth client secret by id",
  [EventType.CREATE_ENVIRONMENT]: "Create environment",
  [EventType.UPDATE_ENVIRONMENT]: "Update environment",
  [EventType.DELETE_ENVIRONMENT]: "Delete environment",
  [EventType.ADD_PROJECT_MEMBER]: "Add member",
  [EventType.REMOVE_PROJECT_MEMBER]: "Remove member",
  [EventType.CREATE_FOLDER]: "Create folder",
  [EventType.UPDATE_FOLDER]: "Update folder",
  [EventType.DELETE_FOLDER]: "Delete folder",
  [EventType.CREATE_WEBHOOK]: "Create webhook",
  [EventType.UPDATE_WEBHOOK_STATUS]: "Update webhook status",
  [EventType.DELETE_WEBHOOK]: "Delete webhook",
  [EventType.WEBHOOK_TRIGGERED]: "Webhook event",
  [EventType.GET_SECRET_IMPORTS]: "List secret imports",
  [EventType.CREATE_SECRET_IMPORT]: "Create secret import",
  [EventType.UPDATE_SECRET_IMPORT]: "Update secret import",
  [EventType.DELETE_SECRET_IMPORT]: "Delete secret import",
  [EventType.UPDATE_USER_PROJECT_DENIED_PERMISSIONS]: "Update denied permissions",
  [EventType.UPDATE_USER_PROJECT_ROLE]: "Update user role",
  [EventType.CREATE_CA]: "Create CA",
  [EventType.GET_CA]: "Get CA",
  [EventType.UPDATE_CA]: "Update CA",
  [EventType.DELETE_CA]: "Delete CA",
  [EventType.GET_CA_CSR]: "Get CA CSR",
  [EventType.GET_CA_CERT]: "Get CA certificate",
  [EventType.SIGN_INTERMEDIATE]: "Sign intermediate",
  [EventType.IMPORT_CA_CERT]: "Import CA certificate",
  [EventType.GET_CA_CRL]: "Get CA CRL",
  [EventType.ISSUE_CERT]: "Request certificate",
  [EventType.IMPORT_CERT]: "Import certificate",
  [EventType.GET_CERT]: "Get certificate",
  [EventType.DELETE_CERT]: "Delete certificate",
  [EventType.REVOKE_CERT]: "Revoke certificate",
  [EventType.GET_CERT_BODY]: "Get certificate body",
  [EventType.GET_CERT_PRIVATE_KEY]: "Get certificate private key",
  [EventType.GET_CERT_BUNDLE]: "Get certificate bundle",
  [EventType.CREATE_PKI_ALERT]: "Create PKI alert",
  [EventType.GET_PKI_ALERT]: "Get PKI alert",
  [EventType.UPDATE_PKI_ALERT]: "Update PKI alert",
  [EventType.DELETE_PKI_ALERT]: "Delete PKI alert",
  [EventType.CREATE_PKI_COLLECTION]: "Create PKI collection",
  [EventType.GET_PKI_COLLECTION]: "Get PKI collection",
  [EventType.UPDATE_PKI_COLLECTION]: "Update PKI collection",
  [EventType.DELETE_PKI_COLLECTION]: "Delete PKI collection",
  [EventType.GET_PKI_COLLECTION_ITEMS]: "Get PKI collection items",
  [EventType.ADD_PKI_COLLECTION_ITEM]: "Add PKI collection item",
  [EventType.DELETE_PKI_COLLECTION_ITEM]: "Delete PKI collection item",
  [EventType.ORG_ADMIN_ACCESS_PROJECT]: "Org admin accessed project",
  [EventType.ORG_ADMIN_BYPASS_SSO]: "Org admin bypassed SSO enforcement",
  [EventType.CREATE_CERTIFICATE_TEMPLATE]: "Create certificate template",
  [EventType.UPDATE_CERTIFICATE_TEMPLATE]: "Update certificate template",
  [EventType.DELETE_CERTIFICATE_TEMPLATE]: "Delete certificate template",
  [EventType.GET_CERTIFICATE_TEMPLATE]: "Get certificate template",
  [EventType.GET_CERTIFICATE_TEMPLATE_EST_CONFIG]: "Get certificate template EST configuration",
  [EventType.CREATE_CERTIFICATE_TEMPLATE_EST_CONFIG]:
    "Create certificate template EST configuration",
  [EventType.UPDATE_CERTIFICATE_TEMPLATE_EST_CONFIG]:
    "Update certificate template EST configuration",
  [EventType.UPDATE_PROJECT_WORKFLOW_INTEGRATION_CONFIG]:
    "Update project workflow integration configuration",
  [EventType.GET_PROJECT_WORKFLOW_INTEGRATION_CONFIG]:
    "Get project workflow integration configuration",
  [EventType.INTEGRATION_SYNCED]: "Integration sync",
  [EventType.CREATE_SHARED_SECRET]: "Create shared secret",
  [EventType.DELETE_SHARED_SECRET]: "Delete shared secret",
  [EventType.READ_SHARED_SECRET]: "Read shared secret",
  [EventType.CREATE_CMEK]: "Create KMS key",
  [EventType.UPDATE_CMEK]: "Update KMS key",
  [EventType.DELETE_CMEK]: "Delete KMS key",
  [EventType.GET_CMEKS]: "List KMS keys",
  [EventType.GET_CMEK]: "Get KMS key",
  [EventType.CMEK_ENCRYPT]: "Encrypt with KMS key",
  [EventType.CMEK_DECRYPT]: "Decrypt with KMS key",
  [EventType.CMEK_SIGN]: "Sign with KMS key",
  [EventType.CMEK_VERIFY]: "Verify with KMS key",
  [EventType.CMEK_LIST_SIGNING_ALGORITHMS]: "List signing algorithms for KMS key",
  [EventType.CMEK_GET_PUBLIC_KEY]: "Get public key for KMS key",
  [EventType.UPDATE_EXTERNAL_GROUP_ORG_ROLE_MAPPINGS]:
    "Update SSO group to organization role mapping",
  [EventType.GET_EXTERNAL_GROUP_ORG_ROLE_MAPPINGS]: "List SSO group to organization role mapping",
  [EventType.GET_PROJECT_TEMPLATES]: "List project templates",
  [EventType.GET_PROJECT_TEMPLATE]: "Get project template",
  [EventType.CREATE_PROJECT_TEMPLATE]: "Create project template",
  [EventType.UPDATE_PROJECT_TEMPLATE]: "Update project template",
  [EventType.DELETE_PROJECT_TEMPLATE]: "Delete project template",
  [EventType.GET_APP_CONNECTIONS]: "List App Connections",
  [EventType.GET_AVAILABLE_APP_CONNECTIONS_DETAILS]: "List App Connections Details",
  [EventType.GET_APP_CONNECTION]: "Get App Connection",
  [EventType.CREATE_APP_CONNECTION]: "Create App Connection",
  [EventType.UPDATE_APP_CONNECTION]: "Update App Connection",
  [EventType.DELETE_APP_CONNECTION]: "Delete App Connection",
  [EventType.GET_APP_CONNECTION_USAGE]: "Get App Connection Usage",
  [EventType.MIGRATE_APP_CONNECTION]: "Migrate App Connection",
  [EventType.GET_SECRET_SYNCS]: "List secret syncs",
  [EventType.GET_SECRET_SYNC]: "Get Secret Sync",
  [EventType.CREATE_SECRET_SYNC]: "Create Secret Sync",
  [EventType.UPDATE_SECRET_SYNC]: "Update Secret Sync",
  [EventType.DELETE_SECRET_SYNC]: "Delete Secret Sync",
  [EventType.SECRET_SYNC_SYNC_SECRETS]: "Secret Sync synced secrets",
  [EventType.SECRET_SYNC_IMPORT_SECRETS]: "Secret Sync imported secrets",
  [EventType.SECRET_SYNC_REMOVE_SECRETS]: "Secret Sync removed secrets",
  [EventType.GET_PKI_SYNCS]: "List PKI syncs",
  [EventType.GET_PKI_SYNC]: "Get PKI sync",
  [EventType.CREATE_PKI_SYNC]: "Create PKI sync",
  [EventType.UPDATE_PKI_SYNC]: "Update PKI sync",
  [EventType.DELETE_PKI_SYNC]: "Delete PKI sync",
  [EventType.PKI_SYNC_SYNC_CERTIFICATES]: "PKI Sync synced certificates",
  [EventType.PKI_SYNC_IMPORT_CERTIFICATES]: "PKI Sync imported certificates",
  [EventType.PKI_SYNC_REMOVE_CERTIFICATES]: "PKI Sync removed certificates",
  [EventType.OIDC_GROUP_MEMBERSHIP_MAPPING_ASSIGN_USER]:
    "OIDC group membership mapping assigned user to groups",
  [EventType.OIDC_GROUP_MEMBERSHIP_MAPPING_REMOVE_USER]:
    "OIDC group membership mapping removed user from groups",
  [EventType.SECRET_APPROVAL_REQUEST_REVIEW]: "Review Secret Approval Request",
  [EventType.CREATE_KMIP_CLIENT]: "Create KMIP client",
  [EventType.UPDATE_KMIP_CLIENT]: "Update KMIP client",
  [EventType.DELETE_KMIP_CLIENT]: "Delete KMIP client",
  [EventType.GET_KMIP_CLIENT]: "Get KMIP client",
  [EventType.GET_KMIP_CLIENTS]: "Get KMIP clients",
  [EventType.CREATE_KMIP_CLIENT_CERTIFICATE]: "Create KMIP client certificate",
  [EventType.SETUP_KMIP]: "Setup KMIP configuration",
  [EventType.GET_KMIP]: "Get KMIP configuration",
  [EventType.REGISTER_KMIP_SERVER]: "Register KMIP server",
  [EventType.KMIP_OPERATION_CREATE]: "KMIP operation create",
  [EventType.KMIP_OPERATION_GET]: "KMIP operation get",
  [EventType.KMIP_OPERATION_DESTROY]: "KMIP operation destroy",
  [EventType.KMIP_OPERATION_GET_ATTRIBUTES]: "KMIP operation get attributes",
  [EventType.KMIP_OPERATION_ACTIVATE]: "KMIP operation activate",
  [EventType.KMIP_OPERATION_REVOKE]: "KMIP operation revoke",
  [EventType.KMIP_OPERATION_LOCATE]: "KMIP operation locate",
  [EventType.KMIP_OPERATION_REGISTER]: "KMIP operation register",
  [EventType.GET_SECRET_ROTATIONS]: "List Secret Rotations",
  [EventType.GET_SECRET_ROTATION]: "Get Secret Rotation",
  [EventType.GET_SECRET_ROTATION_GENERATED_CREDENTIALS]:
    "Get Secret Rotation generated credentials",
  [EventType.CREATE_SECRET_ROTATION]: "Create Secret Rotation",
  [EventType.UPDATE_SECRET_ROTATION]: "Update Secret Rotation",
  [EventType.DELETE_SECRET_ROTATION]: "Delete Secret Rotation",
  [EventType.SECRET_ROTATION_ROTATE_SECRETS]: "Secret Rotation secrets rotated",

  [EventType.GET_PROJECT_SLACK_CONFIG]: "Get Project Slack Config",
  [EventType.UPDATE_PROJECT_SLACK_CONFIG]: "Update Project Slack Config",

  [EventType.MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_CREATE]:
    "Create Microsoft Teams Workflow Integration",
  [EventType.MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_DELETE]:
    "Delete Microsoft Teams Workflow Integration",
  [EventType.MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_UPDATE]:
    "Update Microsoft Teams Workflow Integration",
  [EventType.MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_CHECK_INSTALLATION_STATUS]:
    "Microsoft Teams Workflow Integration Check Installation Status",
  [EventType.MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_GET_TEAMS]: "Get Microsoft Teams tenant teams",
  [EventType.MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_GET]: "Get Microsoft Teams Workflow Integration",
  [EventType.MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_LIST]:
    "List Microsoft Teams Workflow Integration",

  [EventType.LOGIN_IDENTITY_LDAP_AUTH]: "Identity login via LDAP Auth",
  [EventType.ADD_IDENTITY_LDAP_AUTH]: "Attached LDAP Auth to identity",
  [EventType.UPDATE_IDENTITY_LDAP_AUTH]: "Updated LDAP Auth for identity",
  [EventType.GET_IDENTITY_LDAP_AUTH]: "Retrieved LDAP Auth for identity",
  [EventType.REVOKE_IDENTITY_LDAP_AUTH]: "Revoked LDAP Auth for identity",
  [EventType.CLEAR_IDENTITY_LDAP_AUTH_LOCKOUTS]: "Clear LDAP Auth lockouts",

  [EventType.SECRET_SCANNING_DATA_SOURCE_LIST]: "List Secret Scanning Data Sources",
  [EventType.SECRET_SCANNING_DATA_SOURCE_CREATE]: "Create Secret Scanning Data Source",
  [EventType.SECRET_SCANNING_DATA_SOURCE_UPDATE]: "Update Secret Scanning Data Source",
  [EventType.SECRET_SCANNING_DATA_SOURCE_DELETE]: "Delete Secret Scanning Data Source",
  [EventType.SECRET_SCANNING_DATA_SOURCE_GET]: "Get Secret Scanning Data Source",
  [EventType.SECRET_SCANNING_DATA_SOURCE_TRIGGER_SCAN]: "Trigger Secret Scanning Data Source Scan",
  [EventType.SECRET_SCANNING_DATA_SOURCE_SCAN]: "Secret Scanning Data Source Scan",
  [EventType.SECRET_SCANNING_RESOURCE_LIST]: "List Secret Scanning Resources",
  [EventType.SECRET_SCANNING_SCAN_LIST]: "List Secret Scanning Scans",
  [EventType.SECRET_SCANNING_FINDING_LIST]: "List Secret Scanning Findings",
  [EventType.SECRET_SCANNING_FINDING_UPDATE]: "Update Secret Scanning Finding Status",
  [EventType.SECRET_SCANNING_CONFIG_GET]: "Get Secret Scanning Configuration",
  [EventType.SECRET_SCANNING_CONFIG_UPDATE]: "Update Secret Scanning Configuration",

  [EventType.CREATE_PKI_SUBSCRIBER]: "Create PKI subscriber",
  [EventType.UPDATE_PKI_SUBSCRIBER]: "Update PKI subscriber",
  [EventType.DELETE_PKI_SUBSCRIBER]: "Delete PKI subscriber",
  [EventType.GET_PKI_SUBSCRIBER]: "Get PKI subscriber",
  [EventType.ISSUE_PKI_SUBSCRIBER_CERT]: "Request PKI subscriber certificate",
  [EventType.SIGN_PKI_SUBSCRIBER_CERT]: "Sign PKI subscriber certificate",
  [EventType.AUTOMATED_RENEW_SUBSCRIBER_CERT]: "Automated renew PKI subscriber certificate",
  [EventType.LIST_PKI_SUBSCRIBER_CERTS]: "List PKI subscriber certificates",

  [EventType.UPDATE_ORG]: "Update Organization",
  [EventType.CREATE_PROJECT]: "Create Project",
  [EventType.UPDATE_PROJECT]: "Update Project",
  [EventType.DELETE_PROJECT]: "Delete Project",

  [EventType.CREATE_SECRET_REMINDER]: "Create Secret Reminder",
  [EventType.GET_SECRET_REMINDER]: "Get Secret Reminder",
  [EventType.DELETE_SECRET_REMINDER]: "Delete Secret Reminder",

  [EventType.DASHBOARD_LIST_SECRETS]: "Dashboard List Secrets",
  [EventType.DASHBOARD_GET_SECRET_VALUE]: "Dashboard Get Secret Value",
  [EventType.DASHBOARD_GET_SECRET_VERSION_VALUE]: "Dashboard Get Secret Version Value",

  [EventType.CREATE_PROJECT_ROLE]: "Create Project Role",
  [EventType.UPDATE_PROJECT_ROLE]: "Update Project Role",
  [EventType.DELETE_PROJECT_ROLE]: "Delete Project Role",

  [EventType.CREATE_ORG_ROLE]: "Create Org Role",
  [EventType.UPDATE_ORG_ROLE]: "Update Org Role",
  [EventType.DELETE_ORG_ROLE]: "Delete Org Role",

  [EventType.CREATE_SUB_ORGANIZATION]: "Create Sub Organization",
  [EventType.UPDATE_SUB_ORGANIZATION]: "Update Sub Organization",

  [EventType.CREATE_IDENTITY_ORG_MEMBERSHIP]: "Create Identity Org Membership",
  [EventType.UPDATE_IDENTITY_ORG_MEMBERSHIP]: "Update Identity Org Membership",
  [EventType.DELETE_IDENTITY_ORG_MEMBERSHIP]: "Delete Identity Org Membership",

  [EventType.CREATE_IDENTITY_PROJECT_MEMBERSHIP]: "Create Identity Project Membership",
  [EventType.UPDATE_IDENTITY_PROJECT_MEMBERSHIP]: "Update Identity Project Membership",
  [EventType.DELETE_IDENTITY_PROJECT_MEMBERSHIP]: "Delete Identity Project Membership",

  [EventType.PAM_SESSION_CREDENTIALS_GET]: "Get PAM Session Credentials",
  [EventType.PAM_SESSION_START]: "Start PAM Session",
  [EventType.PAM_SESSION_LOGS_UPDATE]: "Update PAM Session Logs",
  [EventType.PAM_SESSION_END]: "End PAM Session",
  [EventType.PAM_SESSION_GET]: "Get PAM Session",
  [EventType.PAM_SESSION_LIST]: "List PAM Sessions",
  [EventType.PAM_FOLDER_CREATE]: "Create PAM Folder",
  [EventType.PAM_FOLDER_UPDATE]: "Update PAM Folder",
  [EventType.PAM_FOLDER_DELETE]: "Delete PAM Folder",
  [EventType.PAM_ACCOUNT_LIST]: "List PAM Accounts",
  [EventType.PAM_ACCOUNT_ACCESS]: "Access PAM Account",
  [EventType.PAM_ACCOUNT_CREATE]: "Create PAM Account",
  [EventType.PAM_ACCOUNT_UPDATE]: "Update PAM Account",
  [EventType.PAM_ACCOUNT_DELETE]: "Delete PAM Account",
  [EventType.PAM_RESOURCE_LIST]: "List PAM Resources",
  [EventType.PAM_RESOURCE_GET]: "Get PAM Resource",
  [EventType.PAM_RESOURCE_CREATE]: "Create PAM Resource",
  [EventType.PAM_RESOURCE_UPDATE]: "Update PAM Resource",
  [EventType.PAM_RESOURCE_DELETE]: "Delete PAM Resource",

  [EventType.CREATE_CERTIFICATE_PROFILE]: "Create Certificate Profile",
  [EventType.UPDATE_CERTIFICATE_PROFILE]: "Update Certificate Profile",
  [EventType.DELETE_CERTIFICATE_PROFILE]: "Delete Certificate Profile",
  [EventType.GET_CERTIFICATE_PROFILE]: "Get Certificate Profile",
  [EventType.LIST_CERTIFICATE_PROFILES]: "List Certificate Profiles",
  [EventType.ISSUE_CERTIFICATE_FROM_PROFILE]: "Request Certificate From Profile",
  [EventType.SIGN_CERTIFICATE_FROM_PROFILE]: "Sign Certificate From Profile",
  [EventType.ORDER_CERTIFICATE_FROM_PROFILE]: "Order Certificate From Profile",
  [EventType.GET_CERTIFICATE_PROFILE_LATEST_ACTIVE_BUNDLE]:
    "Get Certificate Profile Latest Active Bundle",

  [EventType.APPROVAL_POLICY_CREATE]: "Create Approval Policy",
  [EventType.APPROVAL_POLICY_UPDATE]: "Update Approval Policy",
  [EventType.APPROVAL_POLICY_DELETE]: "Delete Approval Policy",
  [EventType.APPROVAL_POLICY_LIST]: "List Approval Policies",
  [EventType.APPROVAL_POLICY_GET]: "Get Approval Policy",
  [EventType.APPROVAL_REQUEST_GET]: "Get Approval Request",
  [EventType.APPROVAL_REQUEST_LIST]: "List Approval Requests",
  [EventType.APPROVAL_REQUEST_CREATE]: "Create Approval Request",
  [EventType.APPROVAL_REQUEST_APPROVE]: "Approve Approval Request",
  [EventType.APPROVAL_REQUEST_REJECT]: "Reject Approval Request",
  [EventType.APPROVAL_REQUEST_CANCEL]: "Cancel Approval Request",
  [EventType.APPROVAL_REQUEST_GRANT_LIST]: "List Approval Request Grants",
  [EventType.APPROVAL_REQUEST_GRANT_GET]: "Get Approval Request Grant",
  [EventType.APPROVAL_REQUEST_GRANT_REVOKE]: "Revoke Approval Request Grant",

  // MCP Endpoints
  [EventType.MCP_ENDPOINT_CREATE]: "Create MCP Endpoint",
  [EventType.MCP_ENDPOINT_UPDATE]: "Update MCP Endpoint",
  [EventType.MCP_ENDPOINT_DELETE]: "Delete MCP Endpoint",
  [EventType.MCP_ENDPOINT_GET]: "Get MCP Endpoint",
  [EventType.MCP_ENDPOINT_LIST]: "List MCP Endpoints",
  [EventType.MCP_ENDPOINT_LIST_TOOLS]: "List MCP Endpoint Tools",
  [EventType.MCP_ENDPOINT_ENABLE_TOOL]: "Enable MCP Endpoint Tool",
  [EventType.MCP_ENDPOINT_DISABLE_TOOL]: "Disable MCP Endpoint Tool",
  [EventType.MCP_ENDPOINT_BULK_UPDATE_TOOLS]: "Bulk Update MCP Endpoint Tools",
  [EventType.MCP_ENDPOINT_OAUTH_CLIENT_REGISTER]: "Register MCP OAuth Client",
  [EventType.MCP_ENDPOINT_OAUTH_AUTHORIZE]: "Authorize MCP OAuth Client",
  [EventType.MCP_ENDPOINT_CONNECT]: "Connect to MCP Endpoint",
  [EventType.MCP_ENDPOINT_SAVE_USER_CREDENTIAL]: "Save MCP Server User Credential",

  // MCP Servers
  [EventType.MCP_SERVER_CREATE]: "Create MCP Server",
  [EventType.MCP_SERVER_UPDATE]: "Update MCP Server",
  [EventType.MCP_SERVER_DELETE]: "Delete MCP Server",
  [EventType.MCP_SERVER_GET]: "Get MCP Server",
  [EventType.MCP_SERVER_LIST]: "List MCP Servers",
  [EventType.MCP_SERVER_LIST_TOOLS]: "List MCP Server Tools",
  [EventType.MCP_SERVER_SYNC_TOOLS]: "Sync MCP Server Tools",

  // MCP Activity Logs
  [EventType.MCP_ACTIVITY_LOG_LIST]: "List MCP Activity Logs"
};

export const userAgentTypeToNameMap: { [K in UserAgentType]: string } = {
  [UserAgentType.WEB]: "Web",
  [UserAgentType.CLI]: "CLI",
  [UserAgentType.K8_OPERATOR]: "K8s operator",
  [UserAgentType.TERRAFORM]: "Terraform",
  [UserAgentType.NODE_SDK]: "InfisicalNodeSDK",
  [UserAgentType.PYTHON_SDK]: "InfisicalPythonSDK",
  [UserAgentType.OTHER]: "Other"
};

const sharedProjectEvents = [
  EventType.ADD_PROJECT_MEMBER,
  EventType.REMOVE_PROJECT_MEMBER,
  EventType.CREATE_PROJECT_ROLE,
  EventType.UPDATE_PROJECT_ROLE,
  EventType.DELETE_PROJECT_ROLE,
  EventType.APPROVAL_POLICY_CREATE,
  EventType.APPROVAL_POLICY_UPDATE,
  EventType.APPROVAL_POLICY_DELETE,
  EventType.APPROVAL_POLICY_LIST,
  EventType.APPROVAL_POLICY_GET,
  EventType.APPROVAL_REQUEST_GET,
  EventType.APPROVAL_REQUEST_LIST,
  EventType.APPROVAL_REQUEST_CREATE,
  EventType.APPROVAL_REQUEST_APPROVE,
  EventType.APPROVAL_REQUEST_REJECT,
  EventType.APPROVAL_REQUEST_CANCEL,
  EventType.APPROVAL_REQUEST_GRANT_LIST,
  EventType.APPROVAL_REQUEST_GRANT_GET,
  EventType.APPROVAL_REQUEST_GRANT_REVOKE
];

export const projectToEventsMap: Partial<Record<ProjectType, EventType[]>> = {
  [ProjectType.PAM]: [
    ...sharedProjectEvents,
    EventType.PAM_SESSION_CREDENTIALS_GET,
    EventType.PAM_SESSION_START,
    EventType.PAM_SESSION_LOGS_UPDATE,
    EventType.PAM_SESSION_END,
    EventType.PAM_SESSION_GET,
    EventType.PAM_SESSION_LIST,
    EventType.PAM_FOLDER_CREATE,
    EventType.PAM_FOLDER_UPDATE,
    EventType.PAM_FOLDER_DELETE,
    EventType.PAM_ACCOUNT_LIST,
    EventType.PAM_ACCOUNT_ACCESS,
    EventType.PAM_ACCOUNT_CREATE,
    EventType.PAM_ACCOUNT_UPDATE,
    EventType.PAM_ACCOUNT_DELETE,
    EventType.PAM_RESOURCE_LIST,
    EventType.PAM_RESOURCE_GET,
    EventType.PAM_RESOURCE_CREATE,
    EventType.PAM_RESOURCE_UPDATE,
    EventType.PAM_RESOURCE_DELETE
  ],
  [ProjectType.AI]: [
    ...sharedProjectEvents,
    // MCP Endpoints
    EventType.MCP_ENDPOINT_CREATE,
    EventType.MCP_ENDPOINT_UPDATE,
    EventType.MCP_ENDPOINT_DELETE,
    EventType.MCP_ENDPOINT_GET,
    EventType.MCP_ENDPOINT_LIST,
    EventType.MCP_ENDPOINT_LIST_TOOLS,
    EventType.MCP_ENDPOINT_ENABLE_TOOL,
    EventType.MCP_ENDPOINT_DISABLE_TOOL,
    EventType.MCP_ENDPOINT_BULK_UPDATE_TOOLS,
    EventType.MCP_ENDPOINT_OAUTH_CLIENT_REGISTER,
    EventType.MCP_ENDPOINT_OAUTH_AUTHORIZE,
    EventType.MCP_ENDPOINT_CONNECT,
    EventType.MCP_ENDPOINT_SAVE_USER_CREDENTIAL,
    // MCP Servers
    EventType.MCP_SERVER_CREATE,
    EventType.MCP_SERVER_UPDATE,
    EventType.MCP_SERVER_DELETE,
    EventType.MCP_SERVER_GET,
    EventType.MCP_SERVER_LIST,
    EventType.MCP_SERVER_LIST_TOOLS,
    EventType.MCP_SERVER_SYNC_TOOLS,
    // MCP Activity Logs
    EventType.MCP_ACTIVITY_LOG_LIST
  ]
};
