export enum ActorType {
  PLATFORM = "platform",
  KMIP_CLIENT = "kmipClient",
  USER = "user",
  SERVICE = "service",
  IDENTITY = "identity",
  ACME_PROFILE = "acmeProfile",
  ACME_ACCOUNT = "acmeAccount",
  UNKNOWN_USER = "unknownUser"
}

export enum UserAgentType {
  WEB = "web",
  CLI = "cli",
  K8_OPERATOR = "k8-operator",
  TERRAFORM = "terraform",
  NODE_SDK = "InfisicalNodeSDK",
  PYTHON_SDK = "InfisicalPythonSDK",
  OTHER = "other"
}

export enum EventType {
  GET_SECRETS = "get-secrets",
  DELETE_SECRETS = "delete-secrets",
  CREATE_SECRETS = "create-secrets",
  UPDATE_SECRETS = "update-secrets",
  GET_SECRET = "get-secret",
  CREATE_SECRET = "create-secret",
  UPDATE_SECRET = "update-secret",
  DELETE_SECRET = "delete-secret",
  GET_PROJECT_KEY = "get-project-key",
  AUTHORIZE_INTEGRATION = "authorize-integration",
  UPDATE_INTEGRATION_AUTH = "update-integration-auth",
  UNAUTHORIZE_INTEGRATION = "unauthorize-integration",
  CREATE_INTEGRATION = "create-integration",
  DELETE_INTEGRATION = "delete-integration",
  ADD_TRUSTED_IP = "add-trusted-ip",
  UPDATE_TRUSTED_IP = "update-trusted-ip",
  DELETE_TRUSTED_IP = "delete-trusted-ip",
  CREATE_SERVICE_TOKEN = "create-service-token", // v2
  DELETE_SERVICE_TOKEN = "delete-service-token", // v2
  CREATE_IDENTITY = "create-identity",
  UPDATE_IDENTITY = "update-identity",
  DELETE_IDENTITY = "delete-identity",
  LOGIN_IDENTITY_UNIVERSAL_AUTH = "login-identity-universal-auth",
  ADD_IDENTITY_UNIVERSAL_AUTH = "add-identity-universal-auth",
  UPDATE_IDENTITY_UNIVERSAL_AUTH = "update-identity-universal-auth",
  GET_IDENTITY_UNIVERSAL_AUTH = "get-identity-universal-auth",
  CREATE_IDENTITY_UNIVERSAL_AUTH_CLIENT_SECRET = "create-identity-universal-auth-client-secret",
  REVOKE_IDENTITY_UNIVERSAL_AUTH_CLIENT_SECRET = "revoke-identity-universal-auth-client-secret",
  CLEAR_IDENTITY_UNIVERSAL_AUTH_LOCKOUTS = "clear-identity-universal-auth-lockouts",
  GET_IDENTITY_UNIVERSAL_AUTH_CLIENT_SECRETS = "get-identity-universal-auth-client-secret",
  GET_IDENTITY_UNIVERSAL_AUTH_CLIENT_SECRET_BY_ID = "get-identity-universal-auth-client-secret-by-id",

  LOGIN_IDENTITY_LDAP_AUTH = "login-identity-ldap-auth",
  ADD_IDENTITY_LDAP_AUTH = "add-identity-ldap-auth",
  UPDATE_IDENTITY_LDAP_AUTH = "update-identity-ldap-auth",
  GET_IDENTITY_LDAP_AUTH = "get-identity-ldap-auth",
  REVOKE_IDENTITY_LDAP_AUTH = "revoke-identity-ldap-auth",
  CLEAR_IDENTITY_LDAP_AUTH_LOCKOUTS = "clear-identity-ldap-auth-lockouts",

  CREATE_ENVIRONMENT = "create-environment",
  UPDATE_ENVIRONMENT = "update-environment",
  DELETE_ENVIRONMENT = "delete-environment",
  ADD_PROJECT_MEMBER = "add-project-member",
  REMOVE_PROJECT_MEMBER = "remove-project-member",
  CREATE_FOLDER = "create-folder",
  UPDATE_FOLDER = "update-folder",
  DELETE_FOLDER = "delete-folder",
  CREATE_WEBHOOK = "create-webhook",
  UPDATE_WEBHOOK_STATUS = "update-webhook-status",
  DELETE_WEBHOOK = "delete-webhook",
  WEBHOOK_TRIGGERED = "webhook-triggered",
  GET_SECRET_IMPORTS = "get-secret-imports",
  CREATE_SECRET_IMPORT = "create-secret-import",
  UPDATE_SECRET_IMPORT = "update-secret-import",
  DELETE_SECRET_IMPORT = "delete-secret-import",
  UPDATE_USER_PROJECT_ROLE = "update-user-project-role",
  UPDATE_USER_PROJECT_DENIED_PERMISSIONS = "update-user-project-denied-permissions",
  CREATE_CA = "create-certificate-authority",
  GET_CA = "get-certificate-authority",
  UPDATE_CA = "update-certificate-authority",
  DELETE_CA = "delete-certificate-authority",
  GET_CA_CSR = "get-certificate-authority-csr",
  GET_CA_CERT = "get-certificate-authority-cert",
  SIGN_INTERMEDIATE = "sign-intermediate",
  IMPORT_CA_CERT = "import-certificate-authority-cert",
  GET_CA_CRL = "get-certificate-authority-crl",
  ISSUE_CERT = "issue-cert",
  IMPORT_CERT = "import-cert",
  GET_CERT = "get-cert",
  DELETE_CERT = "delete-cert",
  REVOKE_CERT = "revoke-cert",
  GET_CERT_BODY = "get-cert-body",
  GET_CERT_PRIVATE_KEY = "get-cert-private-key",
  GET_CERT_BUNDLE = "get-cert-bundle",
  CREATE_PKI_ALERT = "create-pki-alert",
  GET_PKI_ALERT = "get-pki-alert",
  UPDATE_PKI_ALERT = "update-pki-alert",
  DELETE_PKI_ALERT = "delete-pki-alert",
  CREATE_PKI_COLLECTION = "create-pki-collection",
  GET_PKI_COLLECTION = "get-pki-collection",
  UPDATE_PKI_COLLECTION = "update-pki-collection",
  DELETE_PKI_COLLECTION = "delete-pki-collection",
  GET_PKI_COLLECTION_ITEMS = "get-pki-collection-items",
  ADD_PKI_COLLECTION_ITEM = "add-pki-collection-item",
  DELETE_PKI_COLLECTION_ITEM = "delete-pki-collection-item",
  ORG_ADMIN_ACCESS_PROJECT = "org-admin-accessed-project",
  ORG_ADMIN_BYPASS_SSO = "org-admin-bypassed-sso",
  CREATE_CERTIFICATE_TEMPLATE = "create-certificate-template",
  UPDATE_CERTIFICATE_TEMPLATE = "update-certificate-template",
  DELETE_CERTIFICATE_TEMPLATE = "delete-certificate-template",
  GET_CERTIFICATE_TEMPLATE = "get-certificate-template",
  CREATE_CERTIFICATE_TEMPLATE_EST_CONFIG = "create-certificate-template-est-config",
  UPDATE_CERTIFICATE_TEMPLATE_EST_CONFIG = "update-certificate-template-est-config",
  GET_CERTIFICATE_TEMPLATE_EST_CONFIG = "get-certificate-template-est-config",
  UPDATE_PROJECT_WORKFLOW_INTEGRATION_CONFIG = "update-project-workflow-integration-config",
  GET_PROJECT_WORKFLOW_INTEGRATION_CONFIG = "get-project-workflow-integration-config",
  INTEGRATION_SYNCED = "integration-synced",
  CREATE_SHARED_SECRET = "create-shared-secret",
  DELETE_SHARED_SECRET = "delete-shared-secret",
  READ_SHARED_SECRET = "read-shared-secret",
  CREATE_CMEK = "create-cmek",
  UPDATE_CMEK = "update-cmek",
  DELETE_CMEK = "delete-cmek",
  GET_CMEKS = "get-cmeks",
  GET_CMEK = "get-cmek",
  CMEK_ENCRYPT = "cmek-encrypt",
  CMEK_DECRYPT = "cmek-decrypt",
  CMEK_SIGN = "cmek-sign",
  CMEK_VERIFY = "cmek-verify",
  CMEK_LIST_SIGNING_ALGORITHMS = "cmek-list-signing-algorithms",
  CMEK_GET_PUBLIC_KEY = "cmek-get-public-key",
  UPDATE_EXTERNAL_GROUP_ORG_ROLE_MAPPINGS = "update-external-group-org-role-mapping",
  GET_EXTERNAL_GROUP_ORG_ROLE_MAPPINGS = "get-external-group-org-role-mapping",
  GET_PROJECT_TEMPLATES = "get-project-templates",
  GET_PROJECT_TEMPLATE = "get-project-template",
  CREATE_PROJECT_TEMPLATE = "create-project-template",
  UPDATE_PROJECT_TEMPLATE = "update-project-template",
  DELETE_PROJECT_TEMPLATE = "delete-project-template",
  GET_APP_CONNECTIONS = "get-app-connections",
  GET_AVAILABLE_APP_CONNECTIONS_DETAILS = "get-available-app-connections-details",
  GET_APP_CONNECTION = "get-app-connection",
  CREATE_APP_CONNECTION = "create-app-connection",
  UPDATE_APP_CONNECTION = "update-app-connection",
  DELETE_APP_CONNECTION = "delete-app-connection",
  GET_APP_CONNECTION_USAGE = "get-app-connection-usage",
  MIGRATE_APP_CONNECTION = "migrate-app-connection",
  GET_SECRET_SYNCS = "get-secret-syncs",
  GET_SECRET_SYNC = "get-secret-sync",
  CREATE_SECRET_SYNC = "create-secret-sync",
  UPDATE_SECRET_SYNC = "update-secret-sync",
  DELETE_SECRET_SYNC = "delete-secret-sync",
  SECRET_SYNC_SYNC_SECRETS = "secret-sync-sync-secrets",
  SECRET_SYNC_IMPORT_SECRETS = "secret-sync-import-secrets",
  SECRET_SYNC_REMOVE_SECRETS = "secret-sync-remove-secrets",
  GET_PKI_SYNCS = "get-pki-syncs",
  GET_PKI_SYNC = "get-pki-sync",
  CREATE_PKI_SYNC = "create-pki-sync",
  UPDATE_PKI_SYNC = "update-pki-sync",
  DELETE_PKI_SYNC = "delete-pki-sync",
  PKI_SYNC_SYNC_CERTIFICATES = "pki-sync-sync-certificates",
  PKI_SYNC_IMPORT_CERTIFICATES = "pki-sync-import-certificates",
  PKI_SYNC_REMOVE_CERTIFICATES = "pki-sync-remove-certificates",
  OIDC_GROUP_MEMBERSHIP_MAPPING_ASSIGN_USER = "oidc-group-membership-mapping-assign-user",
  OIDC_GROUP_MEMBERSHIP_MAPPING_REMOVE_USER = "oidc-group-membership-mapping-remove-user",
  CREATE_KMIP_CLIENT = "create-kmip-client",
  UPDATE_KMIP_CLIENT = "update-kmip-client",
  DELETE_KMIP_CLIENT = "delete-kmip-client",
  GET_KMIP_CLIENT = "get-kmip-client",
  GET_KMIP_CLIENTS = "get-kmip-clients",
  CREATE_KMIP_CLIENT_CERTIFICATE = "create-kmip-client-certificate",
  SETUP_KMIP = "setup-kmip",
  GET_KMIP = "get-kmip",
  REGISTER_KMIP_SERVER = "register-kmip-server",
  KMIP_OPERATION_CREATE = "kmip-operation-create",
  KMIP_OPERATION_GET = "kmip-operation-get",
  KMIP_OPERATION_DESTROY = "kmip-operation-destroy",
  KMIP_OPERATION_GET_ATTRIBUTES = "kmip-operation-get-attributes",
  KMIP_OPERATION_ACTIVATE = "kmip-operation-activate",
  KMIP_OPERATION_REVOKE = "kmip-operation-revoke",
  KMIP_OPERATION_LOCATE = "kmip-operation-locate",
  KMIP_OPERATION_REGISTER = "kmip-operation-register",
  SECRET_APPROVAL_REQUEST_REVIEW = "secret-approval-request-review",
  GET_SECRET_ROTATIONS = "get-secret-rotations",
  GET_SECRET_ROTATION = "get-secret-rotation",
  GET_SECRET_ROTATION_GENERATED_CREDENTIALS = "get-secret-rotation-generated-credentials",
  CREATE_SECRET_ROTATION = "create-secret-rotation",
  UPDATE_SECRET_ROTATION = "update-secret-rotation",
  DELETE_SECRET_ROTATION = "delete-secret-rotation",
  SECRET_ROTATION_ROTATE_SECRETS = "secret-rotation-rotate-secrets",

  GET_PROJECT_SLACK_CONFIG = "get-project-slack-config",
  UPDATE_PROJECT_SLACK_CONFIG = "update-project-slack-config",

  MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_CREATE = "microsoft-teams-workflow-integration-create",
  MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_DELETE = "microsoft-teams-workflow-integration-delete",
  MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_UPDATE = "microsoft-teams-workflow-integration-update",
  MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_CHECK_INSTALLATION_STATUS = "microsoft-teams-workflow-integration-check-installation-status",
  MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_GET_TEAMS = "microsoft-teams-workflow-integration-get-teams",
  MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_GET = "microsoft-teams-workflow-integration-get",
  MICROSOFT_TEAMS_WORKFLOW_INTEGRATION_LIST = "microsoft-teams-workflow-integration-list",

  SECRET_SCANNING_DATA_SOURCE_LIST = "secret-scanning-data-source-list",
  SECRET_SCANNING_DATA_SOURCE_CREATE = "secret-scanning-data-source-create",
  SECRET_SCANNING_DATA_SOURCE_UPDATE = "secret-scanning-data-source-update",
  SECRET_SCANNING_DATA_SOURCE_DELETE = "secret-scanning-data-source-delete",
  SECRET_SCANNING_DATA_SOURCE_GET = "secret-scanning-data-source-get",
  SECRET_SCANNING_DATA_SOURCE_TRIGGER_SCAN = "secret-scanning-data-source-trigger-scan",
  SECRET_SCANNING_DATA_SOURCE_SCAN = "secret-scanning-data-source-scan",
  SECRET_SCANNING_RESOURCE_LIST = "secret-scanning-resource-list",
  SECRET_SCANNING_SCAN_LIST = "secret-scanning-scan-list",
  SECRET_SCANNING_FINDING_LIST = "secret-scanning-finding-list",
  SECRET_SCANNING_FINDING_UPDATE = "secret-scanning-finding-update",
  SECRET_SCANNING_CONFIG_GET = "secret-scanning-config-get",
  SECRET_SCANNING_CONFIG_UPDATE = "secret-scanning-config-update",

  CREATE_PKI_SUBSCRIBER = "create-pki-subscriber",
  UPDATE_PKI_SUBSCRIBER = "update-pki-subscriber",
  DELETE_PKI_SUBSCRIBER = "delete-pki-subscriber",
  GET_PKI_SUBSCRIBER = "get-pki-subscriber",
  ISSUE_PKI_SUBSCRIBER_CERT = "issue-pki-subscriber-cert",
  SIGN_PKI_SUBSCRIBER_CERT = "sign-pki-subscriber-cert",
  AUTOMATED_RENEW_SUBSCRIBER_CERT = "automated-renew-subscriber-cert",
  LIST_PKI_SUBSCRIBER_CERTS = "list-pki-subscriber-certs",
  UPDATE_ORG = "update-org",

  CREATE_PROJECT = "create-project",
  UPDATE_PROJECT = "update-project",
  DELETE_PROJECT = "delete-project",

  CREATE_SECRET_REMINDER = "create-secret-reminder",
  GET_SECRET_REMINDER = "get-secret-reminder",
  DELETE_SECRET_REMINDER = "delete-secret-reminder",

  DASHBOARD_LIST_SECRETS = "dashboard-list-secrets",
  DASHBOARD_GET_SECRET_VALUE = "dashboard-get-secret-value",
  DASHBOARD_GET_SECRET_VERSION_VALUE = "dashboard-get-secret-version-value",

  CREATE_PROJECT_ROLE = "create-project-role",
  UPDATE_PROJECT_ROLE = "update-project-role",
  DELETE_PROJECT_ROLE = "delete-project-role",

  CREATE_ORG_ROLE = "create-org-role",
  UPDATE_ORG_ROLE = "update-org-role",
  DELETE_ORG_ROLE = "delete-org-role",

  CREATE_SUB_ORGANIZATION = "create-sub-organization",
  UPDATE_SUB_ORGANIZATION = "update-sub-organization",

  CREATE_IDENTITY_ORG_MEMBERSHIP = "create-identity-org-membership",
  UPDATE_IDENTITY_ORG_MEMBERSHIP = "update-identity-org-membership",
  DELETE_IDENTITY_ORG_MEMBERSHIP = "delete-identity-org-membership",

  CREATE_IDENTITY_PROJECT_MEMBERSHIP = "create-identity-project-membership",
  UPDATE_IDENTITY_PROJECT_MEMBERSHIP = "update-identity-project-membership",
  DELETE_IDENTITY_PROJECT_MEMBERSHIP = "delete-identity-project-membership",

  PAM_SESSION_CREDENTIALS_GET = "pam-session-credentials-get",
  PAM_SESSION_START = "pam-session-start",
  PAM_SESSION_LOGS_UPDATE = "pam-session-logs-update",
  PAM_SESSION_END = "pam-session-end",
  PAM_SESSION_GET = "pam-session-get",
  PAM_SESSION_LIST = "pam-session-list",
  PAM_FOLDER_CREATE = "pam-folder-create",
  PAM_FOLDER_UPDATE = "pam-folder-update",
  PAM_FOLDER_DELETE = "pam-folder-delete",
  PAM_ACCOUNT_LIST = "pam-account-list",
  PAM_ACCOUNT_ACCESS = "pam-account-access",
  PAM_ACCOUNT_CREATE = "pam-account-create",
  PAM_ACCOUNT_UPDATE = "pam-account-update",
  PAM_ACCOUNT_DELETE = "pam-account-delete",
  PAM_RESOURCE_LIST = "pam-resource-list",
  PAM_RESOURCE_GET = "pam-resource-get",
  PAM_RESOURCE_CREATE = "pam-resource-create",
  PAM_RESOURCE_UPDATE = "pam-resource-update",
  PAM_RESOURCE_DELETE = "pam-resource-delete",

  CREATE_CERTIFICATE_PROFILE = "create-certificate-profile",
  UPDATE_CERTIFICATE_PROFILE = "update-certificate-profile",
  DELETE_CERTIFICATE_PROFILE = "delete-certificate-profile",
  GET_CERTIFICATE_PROFILE = "get-certificate-profile",
  LIST_CERTIFICATE_PROFILES = "list-certificate-profiles",
  ISSUE_CERTIFICATE_FROM_PROFILE = "issue-certificate-from-profile",
  SIGN_CERTIFICATE_FROM_PROFILE = "sign-certificate-from-profile",
  ORDER_CERTIFICATE_FROM_PROFILE = "order-certificate-from-profile",
  GET_CERTIFICATE_PROFILE_LATEST_ACTIVE_BUNDLE = "get-certificate-profile-latest-active-bundle",

  APPROVAL_POLICY_CREATE = "approval-policy-create",
  APPROVAL_POLICY_UPDATE = "approval-policy-update",
  APPROVAL_POLICY_DELETE = "approval-policy-delete",
  APPROVAL_POLICY_LIST = "approval-policy-list",
  APPROVAL_POLICY_GET = "approval-policy-get",
  APPROVAL_REQUEST_GET = "approval-request-get",
  APPROVAL_REQUEST_LIST = "approval-request-list",
  APPROVAL_REQUEST_CREATE = "approval-request-create",
  APPROVAL_REQUEST_APPROVE = "approval-request-approve",
  APPROVAL_REQUEST_REJECT = "approval-request-reject",
  APPROVAL_REQUEST_CANCEL = "approval-request-cancel",
  APPROVAL_REQUEST_GRANT_LIST = "approval-request-grant-list",
  APPROVAL_REQUEST_GRANT_GET = "approval-request-grant-get",
  APPROVAL_REQUEST_GRANT_REVOKE = "approval-request-grant-revoke",

  // MCP Endpoints
  MCP_ENDPOINT_CREATE = "mcp-endpoint-create",
  MCP_ENDPOINT_UPDATE = "mcp-endpoint-update",
  MCP_ENDPOINT_DELETE = "mcp-endpoint-delete",
  MCP_ENDPOINT_GET = "mcp-endpoint-get",
  MCP_ENDPOINT_LIST = "mcp-endpoint-list",
  MCP_ENDPOINT_LIST_TOOLS = "mcp-endpoint-list-tools",
  MCP_ENDPOINT_ENABLE_TOOL = "mcp-endpoint-enable-tool",
  MCP_ENDPOINT_DISABLE_TOOL = "mcp-endpoint-disable-tool",
  MCP_ENDPOINT_BULK_UPDATE_TOOLS = "mcp-endpoint-bulk-update-tools",
  MCP_ENDPOINT_OAUTH_CLIENT_REGISTER = "mcp-endpoint-oauth-client-register",
  MCP_ENDPOINT_OAUTH_AUTHORIZE = "mcp-endpoint-oauth-authorize",
  MCP_ENDPOINT_CONNECT = "mcp-endpoint-connect",
  MCP_ENDPOINT_SAVE_USER_CREDENTIAL = "mcp-endpoint-save-user-credential",

  // MCP Servers
  MCP_SERVER_CREATE = "mcp-server-create",
  MCP_SERVER_UPDATE = "mcp-server-update",
  MCP_SERVER_DELETE = "mcp-server-delete",
  MCP_SERVER_GET = "mcp-server-get",
  MCP_SERVER_LIST = "mcp-server-list",
  MCP_SERVER_LIST_TOOLS = "mcp-server-list-tools",
  MCP_SERVER_SYNC_TOOLS = "mcp-server-sync-tools",

  // MCP Activity Logs
  MCP_ACTIVITY_LOG_LIST = "mcp-activity-log-list",

  // Dynamic Secrets
  CREATE_DYNAMIC_SECRET = "create-dynamic-secret",
  UPDATE_DYNAMIC_SECRET = "update-dynamic-secret",
  DELETE_DYNAMIC_SECRET = "delete-dynamic-secret",
  GET_DYNAMIC_SECRET = "get-dynamic-secret",
  LIST_DYNAMIC_SECRETS = "list-dynamic-secrets",

  // Dynamic Secret Leases
  CREATE_DYNAMIC_SECRET_LEASE = "create-dynamic-secret-lease",
  DELETE_DYNAMIC_SECRET_LEASE = "delete-dynamic-secret-lease",
  RENEW_DYNAMIC_SECRET_LEASE = "renew-dynamic-secret-lease",
  LIST_DYNAMIC_SECRET_LEASES = "list-dynamic-secret-leases",
  GET_DYNAMIC_SECRET_LEASE = "get-dynamic-secret-lease"
}
