apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infisical.fullname" . }}-config
  labels:
    {{- include "infisical.labels" . | nindent 4 }}
data:
  SITE_URL: {{ .Values.config.siteUrl | quote }}
  PORT: {{ .Values.config.port | quote }}
  TELEMETRY_ENABLED: {{ .Values.config.telemetryEnabled | quote }}
