apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secrets-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8-operator
    app.kubernetes.io/part-of: k8-operator
  {{- include "secrets-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}