export type TCompleteAccountSignupDTO = {
  email: string;
  password: string;
  firstName: string;
  lastName?: string;
  protectedKey: string;
  protectedKeyIV: string;
  protectedKeyTag: string;
  publicKey: string;
  encryptedPrivateKey: string;
  encryptedPrivateKeyIV: string;
  encryptedPrivateKeyTag: string;
  salt: string;
  verifier: string;
  organizationName: string;
  providerAuthToken?: string | null;
  attributionSource?: string | undefined;
  ip: string;
  userAgent: string;
  authorization: string;
};

export type TCompleteAccountInviteDTO = {
  email: string;
  password: string;
  firstName: string;
  lastName?: string;
  protectedKey: string;
  protectedKeyIV: string;
  protectedKeyTag: string;
  publicKey: string;
  encryptedPrivateKey: string;
  encryptedPrivateKeyIV: string;
  encryptedPrivateKeyTag: string;
  salt: string;
  verifier: string;
  ip: string;
  userAgent: string;
  authorization: string;
  tokenMetadata?: string;
};
