const PERMISSION_SA_WORKSPACE_READ = 'read';
const PERMISSION_SA_WORKSPACE_WRITE = 'write';

const PERMISSION_SA_WORKSPACE_SET = new Set([
    PERMISSION_SA_WORKSPACE_READ,
    PERMISSION_SA_WORKSPACE_WRITE
]);

const PERMISSION_SA_SET = new Set([
    PERMISSION_SA_WORKSPACE_READ,
    PERMISSION_SA_WORKSPACE_WRITE
]);

export {
    PERMISSION_SA_WORKSPACE_READ,
    PERMISSION_SA_WORKSPACE_WRITE,
    PERMISSION_SA_WORKSPACE_SET,
    PERMISSION_SA_SET
}