const WORKSPACE_ENCRYPTION_MODE_E2EE = 'e2ee';
const WORKSPACE_ENCRYPTION_MODE_BLIND_INDEXED_E2EE = 'blind-indexed-e2ee';
const WORKSPACE_ENCRYPTION_MODE_NOT_E2EE = 'not-e2ee';

export {
    WORKSPACE_ENCRYPTION_MODE_E2EE,
    WORKSPACE_ENCRYPTION_MODE_BLIND_INDEXED_E2EE,
    WORKSPACE_ENCRYPTION_MODE_NOT_E2EE
}