name: Run Helm Chart Tests for Infisical Standalone Postgres
on:
  pull_request:
    paths:
      - "helm-charts/infisical-standalone-postgres/**"
      - ".github/workflows/run-helm-chart-tests-infisical-standalone-postgres.yml"

jobs:
  test-helm:
    name: Test Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.x"
          check-latest: true

      - name: Add Helm repositories
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --charts helm-charts/infisical-standalone-postgres

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0

      - name: Create namespace
        run: kubectl create namespace infisical-standalone-postgres

      - name: Create Infisical secrets
        run: |
          kubectl create secret generic infisical-secrets \
            --namespace infisical-standalone-postgres \
            --from-literal=AUTH_SECRET=6c1fe4e407b8911c104518103505b218 \
            --from-literal=ENCRYPTION_KEY=6c1fe4e407b8911c104518103505b218 \
            --from-literal=SITE_URL=http://localhost:8080

      - name: Create bootstrap secret
        run: |
          kubectl create secret generic infisical-bootstrap-credentials \
            --namespace infisical-standalone-postgres \
            --from-literal=INFISICAL_ADMIN_EMAIL=admin@example.com \
            --from-literal=INFISICAL_ADMIN_PASSWORD=admin-password

      - name: Run chart-testing (install)
        run: |
          ct install \
            --config ct.yaml \
            --charts helm-charts/infisical-standalone-postgres \
            --helm-extra-args="--timeout=300s" \
            --helm-extra-set-args="--set ingress.nginx.enabled=false --set infisical.autoDatabaseSchemaMigration=false --set infisical.replicaCount=1 --set infisical.image.tag=v0.132.2-postgres --set infisical.autoBootstrap.enabled=true" \
            --namespace infisical-standalone-postgres
