name: Go CLI Tests

on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - "cli/**"

    workflow_dispatch:

    workflow_call:
        secrets:
            CLI_TESTS_UA_CLIENT_ID:
                required: true
            CLI_TESTS_UA_CLIENT_SECRET:
                required: true
            CLI_TESTS_SERVICE_TOKEN:
                required: true
            CLI_TESTS_PROJECT_ID:
                required: true
            CLI_TESTS_ENV_SLUG:
                required: true
            CLI_TESTS_USER_EMAIL:
                required: true
            CLI_TESTS_USER_PASSWORD:
                required: true
            CLI_TESTS_INFISICAL_VAULT_FILE_PASSPHRASE:
                required: true
jobs:
    test:
        defaults:
            run:
                working-directory: ./cli
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21.x"
            - name: Install dependencies
              run: go get .
            - name: Test with the Go CLI
              env:
                  CLI_TESTS_UA_CLIENT_ID: ${{ secrets.CLI_TESTS_UA_CLIENT_ID }}
                  CLI_TESTS_UA_CLIENT_SECRET: ${{ secrets.CLI_TESTS_UA_CLIENT_SECRET }}
                  CLI_TESTS_SERVICE_TOKEN: ${{ secrets.CLI_TESTS_SERVICE_TOKEN }}
                  CLI_TESTS_PROJECT_ID: ${{ secrets.CLI_TESTS_PROJECT_ID }}
                  CLI_TESTS_ENV_SLUG: ${{ secrets.CLI_TESTS_ENV_SLUG }}
                  CLI_TESTS_USER_EMAIL: ${{ secrets.CLI_TESTS_USER_EMAIL }}
                  CLI_TESTS_USER_PASSWORD: ${{ secrets.CLI_TESTS_USER_PASSWORD }}
                #   INFISICAL_VAULT_FILE_PASSPHRASE: ${{ secrets.CLI_TESTS_INFISICAL_VAULT_FILE_PASSPHRASE }}

              run: go test -v -count=1 ./test
